In [1]:
import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from variables_inicio import *
from utils_sql import *

In [33]:
import os

ruta_base = r'C:\Users\DATA\Documents\datos\recepcion_base'

archivo_txt = os.path.join(ruta_base, 'MC_20260301_EFECTIVO_23.txt')
archivo_csv = os.path.join(ruta_base, 'MC_20260301_EFECTIVO_23.csv')

with open(archivo_txt, 'r', encoding='latin-1') as infile, \
     open(archivo_csv, 'w', encoding='utf-8', newline='') as outfile:
    
    outfile.write(infile.read())

print("se genero el archivo CSV correctamente.")

se genero el archivo CSV correctamente.

In [30]:


ruta_base = r'C:\Users\DATA\Documents\datos\recepcion_base'
columnas_consumo=['DNI','CLIENTE','ASIGNACION','CANAL','FECHA','RETAIL','ZONA','PLAZA','CODIGO_AGENCIA','AGENCIA','TELEFONO','DIRECCION','URBANIZACION','MICROZONA','DISTRITO','PROVINCIA','DEPARTAMENTO','TASA','LINEA_ACOTADA','CME_DISPONIBLE','PERFIL','SEGMENTO','SCORE','CODBASE','NOMCOMERCIAL','FLGREPROGRAMADOCOVID19EFE','FECVCTOPROXCUOTACPRC19EFE','CELULAR1','CELULAR2','CELULAR3','CELULAR4','CELULAR5','CELULAR6','CELULAR7','CELULAR8','CELULAR9','CELULAR10','CELULAR11','CELULAR12','CELULAR13','CELULAR14','CELULAR15','EMPRESA1','RANGOSALDO1','EMPRESA2','RANGOSALDO2','EMPRESA3','RANGOSALDO3','TIPOCLIENTE','CEL01','CEL02','CEL03','CEL04','CEL05','CEL06','CEL07','CEL08','CEL09','CEL10','CEL11','CEL12','CEL13','CEL14','CEL15','TELF1','TELF2','TELF3','TELF4','TELF5','TELF6','TELF7','TELF8','FECHA_ENVIO','MES_DURACION_BASE','AÑO_DURACION_BASE','SERVICIO','RETIRO','MARCA','MARCA2','MARCA3','MARCA4','MARCA5','FLAT1','FLAT2','FLAT3','REP1','REP2','DEVUELTO','REP3','REP4','CODCANAL','FECULTASIGNACION','FLGCONVENIO','LINEA_FT','LINEA_HS_RS','LINEA_HS_PLUS','LINEA_FULL','FLGSUBPROCESO_HS','LINEA_FT_RETANQUEO','LINEA_HS_RS_RETANQUEO','LINEA_HS_PLUS_RETANQUEO','LINEA_FULL_RETANQUEO','SITUACIONLABORAL','TIPOINGRESO']
mapeo_columnas = {i: col for i, col in enumerate(columnas_consumo)}
print(mapeo_columnas)

{0: 'DNI', 1: 'CLIENTE', 2: 'ASIGNACION', 3: 'CANAL', 4: 'FECHA', 5: 'RETAIL', 6: 'ZONA', 7: 'PLAZA', 8: 'CODIGO_AGENCIA', 9: 'AGENCIA', 10: 'TELEFONO', 11: 'DIRECCION', 12: 'URBANIZACION', 13: 'MICROZONA', 14: 'DISTRITO', 15: 'PROVINCIA', 16: 'DEPARTAMENTO', 17: 'TASA', 18: 'LINEA_ACOTADA', 19: 'CME_DISPONIBLE', 20: 'PERFIL', 21: 'SEGMENTO', 22: 'SCORE', 23: 'CODBASE', 24: 'NOMCOMERCIAL', 25: 'FLGREPROGRAMADOCOVID19EFE', 26: 'FECVCTOPROXCUOTACPRC19EFE', 27: 'CELULAR1', 28: 'CELULAR2', 29: 'CELULAR3', 30: 'CELULAR4', 31: 'CELULAR5', 32: 'CELULAR6', 33: 'CELULAR7', 34: 'CELULAR8', 35: 'CELULAR9', 36: 'CELULAR10', 37: 'CELULAR11', 38: 'CELULAR12', 39: 'CELULAR13', 40: 'CELULAR14', 41: 'CELULAR15', 42: 'EMPRESA1', 43: 'RANGOSALDO1', 44: 'EMPRESA2', 45: 'RANGOSALDO2', 46: 'EMPRESA3', 47: 'RANGOSALDO3', 48: 'TIPOCLIENTE', 49: 'CEL01', 50: 'CEL02', 51: 'CEL03', 52: 'CEL04', 53: 'CEL05', 54: 'CEL06', 55: 'CEL07', 56: 'CEL08', 57: 'CEL09', 58: 'CEL10', 59: 'CEL11', 60: 'CEL12', 61: 'CEL13', 62: 'CEL14', 63: 'CEL15', 64: 'TELF1', 65: 'TELF2', 66: 'TELF3', 67: 'TELF4', 68: 'TELF5', 69: 'TELF6', 70: 'TELF7', 71: 'TELF8', 72: 'FECHA_ENVIO', 73: 'MES_DURACION_BASE', 74: 'AÑO_DURACION_BASE', 75: 'SERVICIO', 76: 'RETIRO', 77: 'MARCA', 78: 'MARCA2', 79: 'MARCA3', 80: 'MARCA4', 81: 'MARCA5', 82: 'FLAT1', 83: 'FLAT2', 84: 'FLAT3', 85: 'REP1', 86: 'REP2', 87: 'DEVUELTO', 88: 'REP3', 89: 'REP4', 90: 'CODCANAL', 91: 'FECULTASIGNACION', 92: 'FLGCONVENIO', 93: 'LINEA_FT', 94: 'LINEA_HS_RS', 95: 'LINEA_HS_PLUS', 96: 'LINEA_FULL', 97: 'FLGSUBPROCESO_HS', 98: 'LINEA_FT_RETANQUEO', 99: 'LINEA_HS_RS_RETANQUEO', 100: 'LINEA_HS_PLUS_RETANQUEO', 101: 'LINEA_FULL_RETANQUEO', 102: 'SITUACIONLABORAL', 103: 'TIPOINGRESO'}

In [ ]:
col_efe_consumo_carga=['DNI','CLIENTE','ASIGNACION','CANAL','FECHA','RETAIL','ZONA','PLAZA','CODIGO_AGENCIA','AGENCIA','TELEFONO','DIRECCION','URBANIZACION','MICROZONA','DISTRITO','PROVINCIA','DEPARTAMENTO','TASA','LINEA_ACOTADA','CME_DISPONIBLE','PERFIL','SEGMENTO','SCORE','CODBASE','NOMCOMERCIAL','FLGREPROGRAMADOCOVID19EFE','FECVCTOPROXCUOTACPRC19EFE','CELULAR1','CELULAR2','CELULAR3','CELULAR4','CELULAR5','CELULAR6','CELULAR7','CELULAR8','CELULAR9','CELULAR10','CELULAR11','CELULAR12','CELULAR13','CELULAR14','CELULAR15','EMPRESA1','RANGOSALDO1','EMPRESA2','RANGOSALDO2','EMPRESA3','RANGOSALDO3','TIPOCLIENTE','CEL01','CEL02','CEL03','CEL04','CEL05','CEL06','CEL07','CEL08','CEL09','CEL10','CEL11','CEL12','CEL13','CEL14','CEL15','TELF1','TELF2','TELF3','TELF4','TELF5','TELF6','TELF7','TELF8','FECHA_ENVIO','MES_DURACION_BASE','AÑO_DURACION_BASE','SERVICIO','RETIRO','MARCA','MARCA2','MARCA3','MARCA4','MARCA5','FLAT1','FLAT2','FLAT3','REP1','REP2','DEVUELTO','REP3','REP4','CODCANAL','FECULTASIGNACION','FLGCONVENIO','LINEA_FT','LINEA_HS_RS','LINEA_HS_PLUS','LINEA_FULL','FLGSUBPROCESO_HS','LINEA_FT_RETANQUEO','LINEA_HS_RS_RETANQUEO','LINEA_HS_PLUS_RETANQUEO','LINEA_FULL_RETANQUEO','SITUACIONLABORAL','TIPOINGRESO']

col_efe_consumo_en_blanco=['CANAL','FECHA','RETAIL','PLAZA','TELEFONO','DIRECCION','MICROZONA','LINEA_ACOTADA','CELULAR1','CELULAR2','CELULAR3','CELULAR4','CELULAR5','CELULAR6','CELULAR7','CELULAR8','CELULAR9','CELULAR10','CELULAR11','CELULAR12','CELULAR13','CELULAR14','CELULAR15','CEL01','CEL02','CEL03','CEL04','CEL05','CEL06','CEL07','CEL08','CEL09','CEL10','CEL11','CEL12','CEL13','CEL14','CEL15','TELF1','TELF2','TELF3','TELF4','TELF5','TELF6','TELF7','TELF8','RETIRO','MARCA','MARCA2','MARCA3','MARCA4','MARCA5','FLAT1','FLAT2','FLAT3','REP1','REP2','DEVUELTO','REP3','REP4','FLGCONVENIO','LINEA_FT_RETANQUEO','LINEA_HS_RS_RETANQUEO','LINEA_HS_PLUS_RETANQUEO','LINEA_FULL_RETANQUEO']

col_efe_consumo_uno=['FECVCTOPROXCUOTACPRC19EFE','FECHA','RETAIL','PLAZA','TELEFONO','DIRECCION','MICROZONA','LINEA_ACOTADA','CELULAR1','CELULAR2','CELULAR3','CELULAR4','CELULAR5','CELULAR6','CELULAR7','CELULAR8','CELULAR9','CELULAR10','CELULAR11','CELULAR12','CELULAR13','CELULAR14','CELULAR15','CEL01','CEL02','CEL03','CEL04','CEL05','CEL06','CEL07','CEL08','CEL09','CEL10','CEL11','CEL12','CEL13','CEL14','CEL15','TELF1','TELF2','TELF3','TELF4','TELF5','TELF6','TELF7','TELF8','RETIRO','MARCA','MARCA2','MARCA3','MARCA4','MARCA5','FLAT1','FLAT2','FLAT3','REP1','REP2','DEVUELTO','REP3','REP4','FLGCONVENIO','LINEA_FT_RETANQUEO','LINEA_HS_RS_RETANQUEO','LINEA_HS_PLUS_RETANQUEO','LINEA_FULL_RETANQUEO']

col_efe_consumo_rellenar=['FECHA_ENVIO','MES_DURACION_BASE','AÑO_DURACION_BASE','SERVICIO']

In [ ]:
{0: 'DNI', 1: 'CLIENTE', 2: 'ASIGNACION', 3: 'CANAL', 4: 'FECHA', 5: 'RETAIL', 6: 'ZONA', 7: 'PLAZA', 8: 'CODIGO_AGENCIA', 9: 'AGENCIA', 10: 'TELEFONO', 11: 'DIRECCION', 12: 'URBANIZACION', 13: 'MICROZONA', 14: 'DISTRITO', 15: 'PROVINCIA', 16: 'DEPARTAMENTO', 17: 'TASA', 18: 'LINEA_ACOTADA', 19: 'CME_DISPONIBLE', 20: 'PERFIL', 21: 'SEGMENTO', 22: 'SCORE', 23: 'CODBASE', 24: 'NOMCOMERCIAL', 25: 'FLGREPROGRAMADOCOVID19EFE', 26: 'FECVCTOPROXCUOTACPRC19EFE', 27: 'CELULAR1', 28: 'CELULAR2', 29: 'CELULAR3', 30: 'CELULAR4', 31: 'CELULAR5', 32: 'CELULAR6', 33: 'CELULAR7', 34: 'CELULAR8', 35: 'CELULAR9', 36: 'CELULAR10', 37: 'CELULAR11', 38: 'CELULAR12', 39: 'CELULAR13', 40: 'CELULAR14', 41: 'CELULAR15', 42: 'EMPRESA1', 43: 'RANGOSALDO1', 44: 'EMPRESA2', 45: 'RANGOSALDO2', 46: 'EMPRESA3', 47: 'RANGOSALDO3', 48: 'TIPOCLIENTE', 49: 'CEL01', 50: 'CEL02', 51: 'CEL03', 52: 'CEL04', 53: 'CEL05', 54: 'CEL06', 55: 'CEL07', 56: 'CEL08', 57: 'CEL09', 58: 'CEL10', 59: 'CEL11', 60: 'CEL12', 61: 'CEL13', 62: 'CEL14', 63: 'CEL15', 64: 'TELF1', 65: 'TELF2', 66: 'TELF3', 67: 'TELF4', 68: 'TELF5', 69: 'TELF6', 70: 'TELF7', 71: 'TELF8', 72: 'FECHA_ENVIO', 73: 'MES_DURACION_BASE', 74: 'AÑO_DURACION_BASE', 75: 'SERVICIO', 76: 'RETIRO', 77: 'MARCA', 78: 'MARCA2', 79: 'MARCA3', 80: 'MARCA4', 81: 'MARCA5', 82: 'FLAT1', 83: 'FLAT2', 84: 'FLAT3', 85: 'REP1', 86: 'REP2', 87: 'DEVUELTO', 88: 'REP3', 89: 'REP4', 90: 'CODCANAL', 91: 'FECULTASIGNACION', 92: 'FLGCONVENIO', 93: 'LINEA_FT', 94: 'LINEA_HS_RS', 95: 'LINEA_HS_PLUS', 96: 'LINEA_FULL', 97: 'FLGSUBPROCESO_HS', 98: 'LINEA_FT_RETANQUEO', 99: 'LINEA_HS_RS_RETANQUEO', 100: 'LINEA_HS_PLUS_RETANQUEO', 101: 'LINEA_FULL_RETANQUEO', 102: 'SITUACIONLABORAL', 103: 'TIPOINGRESO'}

In [ ]:

archivo = os.path.join(ruta_base, "MC_20260301_EFECTIVO_23.txt")

df = pd.read_csv(
    archivo,
    sep="|",
    header=None,
    encoding="latin-1"
)

C:\Users\DATA\AppData\Local\Temp\ipykernel_14304\1839150752.py:6: DtypeWarning: Columns (0: 31, 1: 32, 2: 33, 3: 34, 4: 35, 5: 36, 6: 37, 7: 38, 8: 39, 9: 40, 10: 41, 11: 42, 12: 43, 13: 44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [ ]:
df.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66],
      dtype='int64')

In [28]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,2026-02-23,2026-01-31,202603,45473216,MAMANI RAFAEL NAPOLION AMADOR,FASTTRACK_202603,NaN,NaN,NaN,SUR,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,INDEPENDIENTE,INGRESO ESTADÍSTICO CLUSTER 3
1,2026-02-23,2026-01-31,202603,7624640,ROJAS ASMAT MARINA YSABEL,DORMIDOS_202603,NaN,NaN,NaN,NORTE 3,...,13500.00,NaN,S,NaN,NaN,NaN,NaN,NaN,INDEPENDIENTE,INGRESO ESTADÍSTICO PREMIUM BATCH
2,2026-02-23,2026-01-31,202603,48566549,VARAS ZAVALETA ROCIO DEL CARMEN,MLRD_202603,NaN,NaN,NaN,NORTE 3,...,2500.00,NaN,S,NaN,NaN,NaN,NaN,NaN,INDEPENDIENTE,INGRESO ESTADÍSTICO CLUSTER 3
3,2026-02-23,2026-01-31,202603,16629398,RODRIGUEZ CALDERON YLEANA BEATRIZ,MLRD_202603,NaN,NaN,NaN,NORTE 2,...,2500.00,NaN,S,NaN,NaN,NaN,NaN,NaN,INDEPENDIENTE,INGRESO ESTADÍSTICO CLUSTER 2
4,2026-02-23,2026-01-31,202603,75861498,GARCIA MENDOZA EUNICE NOEMI,MLRD_202603,NaN,NaN,NaN,NORTE 3,...,618.95,NaN,S,NaN,NaN,NaN,NaN,NaN,INDEPENDIENTE,INGRESO ESTADÍSTICO CLUSTER 3

In [22]:

ruta_base = r'C:\Users\DATA\Documents\datos\recepcion_base'

archivo = os.path.join(ruta_base, "MC_20260301_EFECTIVO_23.txt")

df = pd.read_csv(
    archivo,
    sep="|",
    header=None, 
    encoding="latin-1"
)

C:\Users\DATA\AppData\Local\Temp\ipykernel_14304\3503993617.py:5: DtypeWarning: Columns (0: 31, 1: 32, 2: 33, 3: 34, 4: 35, 5: 36, 6: 37, 7: 38, 8: 39, 9: 40, 10: 41, 11: 42, 12: 43, 13: 44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [19]:
df.shape

(152099, 67)

In [23]:
df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,2026-02-23,2026-01-31,202603,45473216,MAMANI RAFAEL NAPOLION AMADOR,FASTTRACK_202603,NaN,NaN,NaN,SUR,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,INDEPENDIENTE,INGRESO ESTADÍSTICO CLUSTER 3
1,2026-02-23,2026-01-31,202603,7624640,ROJAS ASMAT MARINA YSABEL,DORMIDOS_202603,NaN,NaN,NaN,NORTE 3,...,13500.00,NaN,S,NaN,NaN,NaN,NaN,NaN,INDEPENDIENTE,INGRESO ESTADÍSTICO PREMIUM BATCH
2,2026-02-23,2026-01-31,202603,48566549,VARAS ZAVALETA ROCIO DEL CARMEN,MLRD_202603,NaN,NaN,NaN,NORTE 3,...,2500.00,NaN,S,NaN,NaN,NaN,NaN,NaN,INDEPENDIENTE,INGRESO ESTADÍSTICO CLUSTER 3
3,2026-02-23,2026-01-31,202603,16629398,RODRIGUEZ CALDERON YLEANA BEATRIZ,MLRD_202603,NaN,NaN,NaN,NORTE 2,...,2500.00,NaN,S,NaN,NaN,NaN,NaN,NaN,INDEPENDIENTE,INGRESO ESTADÍSTICO CLUSTER 2
4,2026-02-23,2026-01-31,202603,75861498,GARCIA MENDOZA EUNICE NOEMI,MLRD_202603,NaN,NaN,NaN,NORTE 3,...,618.95,NaN,S,NaN,NaN,NaN,NaN,NaN,INDEPENDIENTE,INGRESO ESTADÍSTICO CLUSTER 3

In [70]:
query = "SELECT * FROM CRONOX.dbo.Llave_Cenco_SAE"
df_cen=get_data_sql(query, params_sa)

# query = "SELECT * FROM CRONOX.dbo.Llave_Financiera_Efe_Neg"
# df_efe_neg=get_data_sql(query, params_sa)

# query = "SELECT * FROM CRONOX.dbo.Llave_Financiera_Efe"
# df_efe_consumo=get_data_sql(query, params_sa)

In [65]:
orden_01=df_efe_consumo.columns.to_list

In [57]:
df_uno=pd.read_excel("C:\\Users\\DATA\\Documents\\datos\\01_script\\inicio\\27-02 SGT.xlsx")

In [58]:
df_uno.columns = (
    df_uno.columns
    .str.strip()
    .str.upper()
    .str.replace("Á","A")
    .str.replace("É","E")
    .str.replace("Í","I")
    .str.replace("Ó","O")
    .str.replace("Ú","U")
)

In [59]:
df_uno['PHONE NUMBER'] = df_uno['NUMERO'].astype(str)

In [60]:
df_uno=df_uno[['DNI', 'NOMBRE', 'PHONE NUMBER']]

In [61]:
df_uno=df_uno.merge(df_efe_consumo, left_on='PHONE NUMBER', right_on='PHONE NUMBER', how='left')

In [ ]:
Index(['LAST NAME', 'FIRST NAME', 'ADDRESS1', 'ADDRESS3', 'COMMENTS',
       'VENDOR LEAD CODE', 'PROVINCE', 'CITY', 'EMAIL', 'COMMENTS_2',
       'PHONE NUMBER', 'Order_Numero', 'Oferta', 'Tip_Prioridad', 'MARCA_2025',
       'NOMCOMERCIAL', 'Perfil_ic', 'tipocliente', 'TIPOINGRESO', 'ASIGNACION',
       'LINEA_FT', 'LINEA_HS_RS', 'LINEA_HS_PLUS', 'LINEA_FULL', 'MARCA',
       'TIP_TELF', 'PROVEEDOR', 'PERFIL', 'SEGMENTO', 'SCORE', 'TASA',
       'RANGO_TASA', 'ZONA', 'Tipo_Telf', 'Fecha_Llam', 'Hora_Llamada',
       'FECHA_ENVIO', 'RETIRO', 'Mejor_Estado_Telefono',
       'Mejor_Sub_Estado_Telefono', 'Mejor_Descripcion_Telefono',
       'Mejor_Fecha_Telefono', 'Mejor_Hora_Telefono', 'Mejor_Durac_Telefono',
       'Mejor_Estado_Cliente', 'Mejor_Sub_Estado_Cliente',
       'Mejor_Descripcion_Cliente', 'Mejor_fecha_Cliente',
       'Mejor_Hora_Cliente', 'Mejor_Durac_Cliente', 'ULT_Descripcion_Cli',
       'ULT_fecha_Cli', 'ULT_Hora_Cli', 'ULT_Durac_Cli', 'ULT_Descripcion_Tel',
       'ULT_fecha_Tel', 'ULT_Hora_Tel', 'ULT_Durac_Tel', 'Veces_Cliente',
       'Veces_Telefono', 'REPITENCIAS', 'Cantidad_Sin_Discador',
       'Cantidad_Discador', 'TELEFO1', 'TELEFO2', 'TELEFO3', 'REGION',
       'MARCADESBASE', 'MARCA2', 'FLGSUBPROCESO_HS', 'SITUACIONLABORAL']pho

Index(['LAST NAME', 'FIRST NAME', 'ADDRESS1', 'ADDRESS3', 'COMMENTS',
       'VENDOR LEAD CODE', 'PROVINCE', 'CITY', 'EMAIL', 'COMMENTS_2',
       'PHONE NUMBER', 'Order_Numero', 'Oferta', 'Tip_Prioridad', 'MARCA_2025',
       'NOMCOMERCIAL', 'Perfil_ic', 'tipocliente', 'TIPOINGRESO', 'ASIGNACION',
       'LINEA_FT', 'LINEA_HS_RS', 'LINEA_HS_PLUS', 'LINEA_FULL', 'MARCA',
       'TIP_TELF', 'PROVEEDOR', 'PERFIL', 'SEGMENTO', 'SCORE', 'TASA',
       'RANGO_TASA', 'ZONA', 'Tipo_Telf', 'Fecha_Llam', 'Hora_Llamada',
       'FECHA_ENVIO', 'RETIRO', 'Mejor_Estado_Telefono',
       'Mejor_Sub_Estado_Telefono', 'Mejor_Descripcion_Telefono',
       'Mejor_Fecha_Telefono', 'Mejor_Hora_Telefono', 'Mejor_Durac_Telefono',
       'Mejor_Estado_Cliente', 'Mejor_Sub_Estado_Cliente',
       'Mejor_Descripcion_Cliente', 'Mejor_fecha_Cliente',
       'Mejor_Hora_Cliente', 'Mejor_Durac_Cliente', 'ULT_Descripcion_Cli',
       'ULT_fecha_Cli', 'ULT_Hora_Cli', 'ULT_Durac_Cli', 'ULT_Descripcion_Tel',
       'ULT_fecha_Tel', 'ULT_Hora_Tel', 'ULT_Durac_Tel', 'Veces_Cliente',
       'Veces_Telefono', 'REPITENCIAS', 'Cantidad_Sin_Discador',
       'Cantidad_Discador', 'TELEFO1', 'TELEFO2', 'TELEFO3', 'REGION',
       'MARCADESBASE', 'MARCA2', 'FLGSUBPROCESO_HS', 'SITUACIONLABORAL'],
      dtype='str')

In [68]:
df_uno=df_uno[['LAST NAME', 'FIRST NAME', 'ADDRESS1', 'ADDRESS3', 'COMMENTS',
       'VENDOR LEAD CODE', 'PROVINCE', 'CITY', 'EMAIL', 'COMMENTS_2',
       'PHONE NUMBER']]

In [ ]:
df_uno

In [69]:
df_uno.to_csv("C:\\Users\\DATA\\Documents\\datos\\01_script\\inicio\\base_01.csv", index=False,sep=';')

(593162, 71)

In [ ]:
# df_efe_consumo['Mejor_Sub_Estado_Cliente'].unique()
    ['Mejor_Descripcion_Cliente'].unique()

<StringArray>
[                             'NO QUIERE',
                 'NO NECESITA / NO DESEA',
                              'SI QUIERE',
                         'ESTA ENDEUDADO',
                        'DESEA MAS MONTO',
                        'VOLVER A LLAMAR',
                                  'OTROS',
                     'CREDITO CONCRETADO',
                         'LO VA A PENSAR',
                       'CLIENTE DE VIAJE',
                     'INTERESES ELEVADOS',
        'TITULAR NO CALIFICA - DESEMPLEO',
                        'ABONO EN CUENTA',
            'CASA EN ZONA NO COBERTURADA',
                  'SOLICITA SER RETIRADO',
         'NEGOCIO EN ZONA NO COBERTURADA',
             'MALA EXPERIENCIA (TDA/FNC)',
 'TITULAR NO CALIFICA- GIRO RESTRINGIDO9',
                         'CONFIRMAR CITA',
      'TITULAR CONTAGIADO CON COVID - 19',
                          'DESEA ELECTRO',
                      'CLIENTE RECHAZADO']
Length: 22, dtype: str

In [54]:
df_efe_consumo[df_efe_consumo['VENDOR LEAD CODE']=='47905540'].head()

Empty DataFrame
Columns: [LAST NAME, FIRST NAME, ADDRESS1, ADDRESS3, COMMENTS, VENDOR LEAD CODE, PROVINCE, CITY, EMAIL, COMMENTS_2, PHONE NUMBER, Order_Numero, Oferta, Tip_Prioridad, MARCA_2025, NOMCOMERCIAL, Perfil_ic, tipocliente, TIPOINGRESO, ASIGNACION, LINEA_FT, LINEA_HS_RS, LINEA_HS_PLUS, LINEA_FULL, MARCA, TIP_TELF, PROVEEDOR, PERFIL, SEGMENTO, SCORE, TASA, RANGO_TASA, ZONA, Tipo_Telf, Fecha_Llam, Hora_Llamada, FECHA_ENVIO, RETIRO, Mejor_Estado_Telefono, Mejor_Sub_Estado_Telefono, Mejor_Descripcion_Telefono, Mejor_Fecha_Telefono, Mejor_Hora_Telefono, Mejor_Durac_Telefono, Mejor_Estado_Cliente, Mejor_Sub_Estado_Cliente, Mejor_Descripcion_Cliente, Mejor_fecha_Cliente, Mejor_Hora_Cliente, Mejor_Durac_Cliente, ULT_Descripcion_Cli, ULT_fecha_Cli, ULT_Hora_Cli, ULT_Durac_Cli, ULT_Descripcion_Tel, ULT_fecha_Tel, ULT_Hora_Tel, ULT_Durac_Tel, Veces_Cliente, Veces_Telefono, REPITENCIAS, Cantidad_Sin_Discador, Cantidad_Discador, TELEFO1, TELEFO2, TELEFO3, REGION, MARCADESBASE, MARCA2, FLGSUBPROCESO_HS, SITUACIONLABORAL]
Index: []

[0 rows x 71 columns]

In [10]:
df_efe_consumo.columns

Index(['LAST NAME', 'FIRST NAME', 'ADDRESS1', 'ADDRESS3', 'COMMENTS',
       'VENDOR LEAD CODE', 'PROVINCE', 'CITY', 'EMAIL', 'COMMENTS_2',
       'PHONE NUMBER', 'Order_Numero', 'Oferta', 'Tip_Prioridad', 'MARCA_2025',
       'NOMCOMERCIAL', 'Perfil_ic', 'tipocliente', 'TIPOINGRESO', 'ASIGNACION',
       'LINEA_FT', 'LINEA_HS_RS', 'LINEA_HS_PLUS', 'LINEA_FULL', 'MARCA',
       'TIP_TELF', 'PROVEEDOR', 'PERFIL', 'SEGMENTO', 'SCORE', 'TASA',
       'RANGO_TASA', 'ZONA', 'Tipo_Telf', 'Fecha_Llam', 'Hora_Llamada',
       'FECHA_ENVIO', 'RETIRO', 'Mejor_Estado_Telefono',
       'Mejor_Sub_Estado_Telefono', 'Mejor_Descripcion_Telefono',
       'Mejor_Fecha_Telefono', 'Mejor_Hora_Telefono', 'Mejor_Durac_Telefono',
       'Mejor_Estado_Cliente', 'Mejor_Sub_Estado_Cliente',
       'Mejor_Descripcion_Cliente', 'Mejor_fecha_Cliente',
       'Mejor_Hora_Cliente', 'Mejor_Durac_Cliente', 'ULT_Descripcion_Cli',
       'ULT_fecha_Cli', 'ULT_Hora_Cli', 'ULT_Durac_Cli', 'ULT_Descripcion_Tel',
       'ULT_fecha_Tel', 'ULT_Hora_Tel', 'ULT_Durac_Tel', 'Veces_Cliente',
       'Veces_Telefono', 'REPITENCIAS', 'Cantidad_Sin_Discador',
       'Cantidad_Discador', 'TELEFO1', 'TELEFO2', 'TELEFO3', 'REGION',
       'MARCADESBASE', 'MARCA2', 'FLGSUBPROCESO_HS', 'SITUACIONLABORAL'],
      dtype='str')