### Validamos base

In [ ]:
BASE_CEL_TARGET_20260901

In [1]:

import sys 
from sqlalchemy import create_engine, text

import numpy as np
import sys 
sys.path.append('C:/Users/Data/Documents/lazo_fernando/target_script_01/funciones')
from funciones import *
from variables_inicio import *
from funciones_spark import *
from utils_sql import *

spark = SparkSession.builder \
    .appName("SparkExample") \
    .master("local[*]") \
    .config('spark.driver.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.4.0.jre11.jar') \
    .config('spark.executor.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.4.0.jre11.jar') \
    .config('spark.executor.memory', '8g') \
    .config('spark.driver.memory', '8g') \
    .getOrCreate()


server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
server_sql = server_zeus
db_sql = "odin"
user_sql = user_zeus
pwd_sql = pwd_zeus

engine_odin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

server_sql = server_zeus
db_sql = "SAMANTHA"
user_sql = user_zeus
pwd_sql = pwd_zeus

engine_samantha = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)


engine_mysql = create_engine(
    f"mysql+pymysql://{user_envio}:{pwd_envio}@{server_envio}:{port_mysql}/{db_envio}"
)



fecha_mes_base='2026-09-01'

In [2]:
from pyspark.sql import functions as F

def completar_dni(df, columna="DNI"):
    return df.withColumn(
        columna,
        F.lpad(F.col(columna).cast("string"), 8, "0")
    )

In [16]:
query = """
    select *   
    from DANTALION.dbo.Base_Maestra_ALFIN_BK
    where fecha_envio>='2026-08-01'
    and fecha_envio<'2026-09-01'
    and lote<>'INVENTARIO'
    """
df_agosto=obtener_tabla_sql(spark,query,server_kishin,user_kishin,pwd_kishin,db_kishin)

In [ ]:
query = """
    select *   
    from DANTALION.dbo.Base_Maestra_Alfin_bk_sep
    """
df_setiembre=obtener_tabla_sql(spark,query,server_kishin,user_kishin,pwd_kishin,db_kishin)

In [ ]:
set_set_agosto = set(df_agosto.select("NUMERO_DOCUMENTO").rdd.flatMap(lambda x: x).collect())
set_set_septiembre = set(df_setiembre.select("NUMERO_DOCUMENTO").rdd

In [17]:
agost.set=set(df_agosto.columns)

NameError: name 'agost' is not defined

In [24]:
agost_set=set(df_agosto.columns)
set_set_septiembre = set(df_setiembre.columns)

In [26]:
print(agost_set & set_set_septiembre)

{'Region_comercial', 'SALDO_DIFERENCIAL_REENG', 'TIPO_CLIENTE', 'Tasa_7', 'OFERTA_MAX', 'CRUCE', 'DEPARTAMENTO', 'Tasa_6', 'RANGO_EDAD', 'GRUPO_MONTO', 'INTENSIDAD_MAX', 'MGNEG', 'APELLIDO_PATERNO', 'Fecha_Envio', 'PROVINCIA', 'PLAZO', 'Tasa_2', 'DISTRITO', 'cl_base', 'Tasa_3', 'color_final', 'NOMBRES', 'Agencia_comercial', 'cl_telf1', 'NUMERO_DOCUMENTO', 'FRESCURA', 'MES_DURACION_BASE', 'CUOTA', 'GRUPO_TASA', 'APELLIDO_MATERNO', 'tipo_cliente_riegos', 'Tasa_1', 'Tasa_5', 'CAPACIDAD_MAX', 'RETIRO', 'SERVICIO', 'lote', 'cl_telf2', 'Edad', 'Tasa_4', 'campania', 'TIPO_BASE', 'PROPENSION_IC', 'RANGO_SUELDO', 'ACCION', 'RANGO_OFERTA', 'USER_V3', 'FLG_AAHH'}

In [35]:
df_agosto=df_agosto.select(
 F.col('OFERTA_MAX').alias('OFERTA_MAX_agosto'),
 'NUMERO_DOCUMENTO',
 F.col('Tasa_1').alias('Tasa_1_agosto')
 )
df_setiembre=df_setiembre.select('Region_comercial', 'SALDO_DIFERENCIAL_REENG', 'TIPO_CLIENTE', 'Tasa_7', 'OFERTA_MAX', 'CRUCE', 'DEPARTAMENTO', 'Tasa_6', 'RANGO_EDAD', 'GRUPO_MONTO', 'INTENSIDAD_MAX', 'MGNEG', 'APELLIDO_PATERNO', 'Fecha_Envio', 'PROVINCIA', 'PLAZO', 'Tasa_2', 'DISTRITO', 'cl_base', 'Tasa_3', 'color_final', 'NOMBRES', 'Agencia_comercial', 'cl_telf1', 'NUMERO_DOCUMENTO', 'FRESCURA', 'MES_DURACION_BASE', 'CUOTA', 'GRUPO_TASA', 'APELLIDO_MATERNO', 'tipo_cliente_riegos', 'Tasa_1', 'Tasa_5', 'CAPACIDAD_MAX', 'RETIRO', 'SERVICIO', 'lote', 'cl_telf2', 'Edad', 'Tasa_4', 'campania', 'TIPO_BASE', 'PROPENSION_IC', 'RANGO_SUELDO', 'ACCION', 'RANGO_OFERTA', 'USER_V3', 'FLG_AAHH')

In [ ]:
df_agosto=df_agosto.

In [36]:
df_01=df_agosto.join(df_setiembre,['NUMERO_DOCUMENTO'],'inner')

In [28]:
df_base=df_agosto.union(df_setiembre)

In [38]:
df_base_pd=df_01.toPandas()

In [39]:

ruta_archivo = os.path.join(ruta_alfin, 'base_alfin.csv')
df_base_pd.to_csv(ruta_archivo, sep=';')

In [30]:
print([row['Tasa_1' ] for row in df_base.select('Tasa_1').distinct().collect()])

[74.5, 70.0, 67.0, 69.0, 76.5, 59.5, 73.5, 67.5, 52.5, 88.0, 49.0, 66.5, 98.0, 64.0, 75.0, 47.0, 81.5, 62.0, 96.0, None, 80.0, 86.0, 64.5, 94.0, 68.5, 85.0, 77.0, 77.5, 50.0, 56.0, 65.5, 78.0, 48.5, 79.0, 83.0, 45.0, 54.5, 57.5, 71.0, 93.0, 50.5, 58.0, 72.0, 51.0, 63.0, 48.0, 82.0, 60.0, 74.0, 66.0, 75.5, 68.0, 53.0, 61.0, 53.5, 81.0, 59.0, 46.0, 78.5, 57.0, 87.0, 60.5, 69.5, 73.0, 87.5, 99.0, 95.0, 102.0, 84.0, 92.0, 52.0, 97.0, 62.5, 89.0, 55.0, 70.5, 55.5, 84.5, 65.0, 51.5, 54.0, 76.0, 90.0, 91.0, 101.0, 104.0, 100.0]

In [ ]:
[74.5, 70.0, 67.0, 69.0, 76.5, 59.5, 73.5, 67.5, 52.5, 88.0, 49.0, 66.5, 98.0, 64.0, 75.0, 47.0, 81.5, 62.0, 96.0, None, 80.0, 86.0, 64.5, 94.0, 68.5, 85.0, 77.0, 77.5, 50.0, 56.0, 65.5, 78.0, 48.5, 79.0, 83.0, 45.0, 54.5, 57.5, 71.0, 93.0, 50.5, 58.0, 72.0, 51.0, 63.0, 48.0, 82.0, 60.0, 74.0, 66.0, 75.5, 68.0, 53.0, 61.0, 53.5, 81.0, 59.0, 46.0, 78.5, 57.0, 87.0, 60.5, 69.5, 73.0, 87.5, 99.0, 95.0, 102.0, 84.0, 92.0, 52.0, 97.0, 62.5, 89.0, 55.0, 70.5, 55.5, 84.5, 65.0, 51.5, 54.0, 76.0, 90.0, 91.0, 101.0, 104.0, 100.0]

In [4]:
filename='BASE_CEL_TARGET_20260901.txt'
df_score=cargar_archivo_csv_ruta(spark,filename,'|',True,ruta_alfin)
filename='BASE_TARGET_20260901.txt'

df_base=cargar_archivo_csv_ruta(spark,filename,'|',True,ruta_alfin)

exprs = [
    F.count(F.when(F.col(c).isNotNull(), c)).alias(c)
    for c in df_base.columns
]

df_counts = df_base.agg(*exprs).collect()[0].asDict()

cols_con_data = [c for c, v in df_counts.items() if v > 0]

df_base = df_base.select(cols_con_data)
df_base=df_base.drop('INTENSIDAD_MAX')

df_base=df_base.withColumnRenamed('DNI','NUMERO_DOCUMENTO')
df_base=df_base.withColumnRenamed('CET','cl_telf1')
df_base=df_base.withColumnRenamed('CEL1','cl_telf2')

df_base=df_base.withColumnRenamed('COLOR','color')
df_base=df_base.withColumnRenamed('REGION_COMERCIAL','Region_comercial')
df_base=df_base.withColumnRenamed('AGENCIA_COMERCIAL','Agencia_comercial')
df_base=df_base.withColumnRenamed('CAMPAÑA','campania')
df_base=df_base.withColumnRenamed('TIPO_CLIENTE_COMERCIAL','tipo_cliente_riegos')
df_base=df_base.withColumnRenamed('CLIENTE','NOMBRES')
df_base=df_base.withColumnRenamed('OFERTA_COMPETITIVA','PEER')
df_base=df_base.withColumnRenamed('PROP','PROPENSION')
# df_base=df_base.withColumnRenamed('DIRECCION','Ubicacion')
df_base=df_base.withColumnRenamed('CAPACIDAD DE PAGO','CAPACIDAD_MAX')
# df_base=df_base.withColumnRenamed('OFERTA_NETA','OFERTA_MAX')

df_base=df_base.withColumnRenamed('X_APPATERNO','APELLIDO_PATERNO')
df_base=df_base.withColumnRenamed('X_APMATERNO','APELLIDO_MATERNO')
df_base=df_base.withColumnRenamed('X_NOMBRE','NOMBRES')
df_base=df_base.drop('VARIACION_OFERTA_CAMPAÑA_ANTERIOR', 'VARIACION_TASA_CAMPAÑA_ANTERIOR', 'CAMP_ADP', 'tasa_minima', 'FLAG_DEUDA_V_OFERTA')


df_score=df_score.withColumnRenamed('dni','NUMERO_DOCUMENTO')
df_score=df_score.withColumnRenamed('CET','cl_telf1')
df_score=df_score.withColumnRenamed('CEL1','cl_telf2')
df_score=df_score.withColumnRenamed('SCORE_TELEFONO','INTENSIDAD_MAX')

df_base=df_base.join(df_score,['NUMERO_DOCUMENTO'],'left')

In [5]:
df_base=df_base.dropDuplicates(['NUMERO_DOCUMENTO'])

In [6]:
print(df_base.filter(F.col('cl_telf1').isNotNull()|F.col('cl_telf2').isNotNull()).count())
print(df_base.count())

172713
180180

In [ ]:

filename='subir_11.csv'
df_base=cargar_archivo_csv_ruta(spark,filename,';',True,ruta_alfin)

filename='Consulta_de_Campañas_202608_V3_SS_02.csv'
df_validar_01=cargar_archivo_csv_ruta(spark,filename,';',True,ruta_alfin)
filename='Consulta_de_Campañas_202608_V3_SS_01.csv'
df_validar_02=cargar_archivo_csv_ruta(spark,filename,';',True,ruta_alfin)
filename='Consulta_de_Campañas_202608_V3_SS_03.csv'
df_validar_03=cargar_archivo_csv_ruta(spark,filename,';',True,ruta_alfin)
filename='Consulta_de_Campañas_202608_V3_SS_04.csv'
df_validar_04=cargar_archivo_csv_ruta(spark,filename,';',True,ruta_alfin)
df_validar=df_validar_01.unionByName(df_validar_02).unionByName(df_validar_03).unionByName(df_validar_04)
df_validar=df_validar.dropDuplicates(['DNI'])

df_validar=df_validar.withColumnRenamed('tasa_1','Tasa_1')
df_validar=df_validar.withColumnRenamed('tasa_2','Tasa_2')
df_validar=df_validar.withColumnRenamed('tasa_3','Tasa_3')
df_validar=df_validar.withColumnRenamed('tasa_4','Tasa_4')
df_validar=df_validar.withColumnRenamed('tasa_5','Tasa_5')
df_validar=df_validar.withColumnRenamed('tasa_6','Tasa_6')
df_validar=df_validar.withColumnRenamed('tasa_7','Tasa_7')
df_validar=df_validar.withColumnRenamed('oferta_max','OFERTA_MAX')
df_validar=df_validar.withColumnRenamed('DNI','NUMERO_DOCUMENTO')
df_validar=df_validar.withColumnRenamed('campaña','campania')
df_validar=df_validar.withColumnRenamed('COLOR_FINAL','color_final')
df_validar=df_validar.withColumnRenamed('PROPENSION_DISTRIBUCION','PROPENSION_IC')

In [44]:

# df_validar=completar_dni(df_validar,'NUMERO_DOCUMENTO')
# df_score=completar_dni(df_score,'NUMERO_DOCUMENTO')
# df_base=completar_dni(df_base,'NUMERO_DOCUMENTO')

In [16]:
print(df_base.columns)['NUMERO_DOCUMENTO', 'PROPENSION_IC', 'USER_V3', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'NOMBRES', 'OFERTA_MAX', 'PLAZO', 'CUOTA', 'CAPACIDAD_MAX', 'tipo_cliente_riegos', 'campania', 'SALDO_DIFERENCIAL_REENG', 'TIPO_CLIENTE', 'color_final', 'TIPO_BASE', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'Agencia_comercial', 'Region_comercial', 'GRUPO_TASA', 'GRUPO_MONTO', 'MGNEG', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'Edad', 'RANGO_EDAD', 'RANGO_OFERTA', 'RANGO_SUELDO', 'FRESCURA', 'FLG_AAHH', 'ACCION', 'cl_telf1', 'cl_telf2', 'INTENSIDAD_MAX']

['NUMERO_DOCUMENTO', 'PROPENSION_IC', 'USER_V3', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'NOMBRES', 'OFERTA_MAX', 'PLAZO', 'CUOTA', 'CAPACIDAD_MAX', 'tipo_cliente_riegos', 'campania', 'SALDO_DIFERENCIAL_REENG', 'TIPO_CLIENTE', 'color_final', 'TIPO_BASE', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'Agencia_comercial', 'Region_comercial', 'GRUPO_TASA', 'GRUPO_MONTO', 'MGNEG', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'Edad', 'RANGO_EDAD', 'RANGO_OFERTA', 'RANGO_SUELDO', 'FRESCURA', 'FLG_AAHH', 'ACCION', 'cl_telf1', 'cl_telf2', 'INTENSIDAD_MAX']

In [24]:
formato_set=set(df_formato.columns)
base_set=set(df_base.columns)
consulta_campana_set=set(df_validar.columns)

# print(base_set-consulta_campana_set)
# print(consulta_campana_set-base_set)
# print(consulta_campana_set & base_set)
print(formato_set-base_set)
print(base_set-formato_set)
print(base_set&formato_set)

# print(base_set-formato_set)

{'SERVICIO', 'TEM', 'RETIRO', 'PROPENSION', 'cl_telefono', 'TIPO_BD', 'LEAD_CALIDAD', 'Nombre_prioridad', 'Entidad_2', 'marca2', 'flag_deuda_v_oferta', 'FLG_DEUDA_PLUS', 'Oferta_24M', 'Desgravamen_36M', 'PILOTO_PLAZAS', 'Tasa_36M', 'NUEVOS_6M', 'cl_gestor', 'PERIODO', 'GRUPO_TASA_REENGANCHE', 'cl_fecha_llamar', 'cl_mes', 'Ubicacion', 'cl_gestion', 'cl_accion_ant', 'NUEVOS_4M', 'PREST_PREVIO', 'PILOTO_RETENCION', 'NUEVOS_3M', 'fecha_alimentacion', 'SUCURSAL', 'NUEVOS_12M', 'Fecha_Envio', 'Entidad_1', 'Campana', 'cl_fecha_ant', 'RANGO_EDAD2', 'COD_BD', 'PROMOCION', 'RETIRO_GEST', 'TIENDA', 'cl_movil', 'Tasa_24M', 'Oferta_36M', 'MONTO_DESEMBOLSADO', 'FLAG_REENG', 'Oferta_12M', 'Deuda_3', 'RETIRO_DESEMBOLSO', 'cl_orden', 'marca3', 'CUOTA_24M', 'TIPO_DOI', 'lote', 'Deuda_1', 'cl_celular', 'segmento', 'MES_GESTION', 'cl_telf9', 'GARANTIA', 'cl_telf7', 'Deuda_2', 'STATUS', 'cl_predictivo', 'cl_telf8', 'color', 'PERFIL_RO', 'FEC_NACIMIENTO', 'incremento_monto_riesgos', 'CAMP_BONO', 'PEER', 'MES_DURACION_BASE', 'TASA_VS_MONTO', 'RESULTADO', 'Desgravamen', 'cl_base_ant', 'Desgravamen_18M', 'REP1', 'Q_VENTAS', 'Prioridad', 'OFERTA_FINAL', 'PROP_COMER', 'REP2', 'Oferta_Minima_Paperless', 'CRUCE', 'cl_turno', 'GRUPO_RIESGO', 'nombre_base', 'cl_telf10', 'OfertaMaximaSinSeguro', 'Tasa_18M', 'Oferta_18M', 'FLAT2', 'NUM_ENRIQUECIDO', 'Validador_Telefono', 'sucursal_comercial', 'SEGMENTO_USER', 'cl_telf4', 'cl_tiempo', 'cl_telf6', 'CUOTA_18M', 'cl_area', 'id_carga', 'NumEntidades', 'TIPO_GEST', 'DESEMBOLSADO', 'cl_telf3', 'AÑO_DURACION_BASE', 'USUARIO', 'MEJOR_TIPIFICACION', 'CUOTA_12M', 'SBI', 'PROMOCION2', 'NOMB_BD', 'NUEVOS_9M', 'cl_accion', 'cl_hits', 'BASE', 'cl_hora_gestion', 'CLIENTE_NUEVO', 'marca1', 'Entidad_3', 'cl_prioridad', 'Desgravamen_24M', 'p_banco', 'RANGO_OFERTA2', 'Tasa_12M', 'LOCALIDAD', 'SCORE_TELEFONO', 'FECHA_SOL', 'OFERTA_REEN', 'cl_telf5', 'cl_carga', 'PERFIL_GLOBAL', 'ID_CLIENTE', 'cl_base', 'Desgravamen_12M', 'TIPO_CONTACTO', 'proveedor', 'CUOTA_36M', 'Tipo_verificacion', 'cl_asesor', 'cl_fecha_gestion'}
set()
{'TIPO_BASE', 'FRESCURA', 'RANGO_EDAD', 'campania', 'PROVINCIA', 'NOMBRES', 'SALDO_DIFERENCIAL_REENG', 'Agencia_comercial', 'tipo_cliente_riegos', 'INTENSIDAD_MAX', 'Tasa_2', 'MGNEG', 'PROPENSION_IC', 'Region_comercial', 'color_final', 'APELLIDO_PATERNO', 'Edad', 'GRUPO_MONTO', 'Tasa_6', 'DISTRITO', 'PLAZO', 'Tasa_4', 'NUMERO_DOCUMENTO', 'FLG_AAHH', 'CAPACIDAD_MAX', 'GRUPO_TASA', 'USER_V3', 'CUOTA', 'RANGO_OFERTA', 'DEPARTAMENTO', 'cl_telf1', 'RANGO_SUELDO', 'OFERTA_MAX', 'cl_telf2', 'Tasa_3', 'Tasa_5', 'Tasa_1', 'TIPO_CLIENTE', 'Tasa_7', 'APELLIDO_MATERNO', 'ACCION'}

In [19]:
df_validar=df_validar.drop(
   'rango_deuda', 'TIPO', 'AUTORIZACION_DATOS', 'FLAG_DEUDA_V_OFERTA', 'TASA_6_SS', 'TASA_7_SS', 'TASA_4_SS', 'TASA_1_SS', 'TASA_5_SS', 'COD_USER_V3', 'numentidades', 'OFERTA_SS', 'TASA_3_SS', 'TASA_2_SS', 'ALERTA_MAQUETA', 'FEN', 'PERFIL_RO', 'PERFIL_ESPECIAL', 'TOTAL_A_LIQUIDAR', 'MARCA_PD', 'TASA_CREDITO_ANTERIOR'


)

In [ ]:
df_base=df_base.drop(
'TIPO_BASE', 'FRESCURA', 'campania', 'Tasa_2', 'MGNEG', 'PROPENSION_IC', 'color_final', 'Tasa_6', 'PLAZO', 'Tasa_4', 'CAPACIDAD_MAX', 'GRUPO_TASA', 'USER_V3', 'OFERTA_MAX', 'Tasa_3', 'Tasa_5', 'Tasa_1', 'Tasa_7'
)

In [22]:
df_base=df_base.join(df_validar,['NUMERO_DOCUMENTO'],'left')
df_base=df_base.dropDuplicates(['NUMERO_DOCUMENTO'])

In [26]:
['NUMERO_DOCUMENTO', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'NOMBRES', 'CUOTA', 'tipo_cliente_riegos', 'SALDO_DIFERENCIAL_REENG', 'TIPO_CLIENTE', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'Agencia_comercial', 'Region_comercial', 'GRUPO_MONTO', 'Edad', 'RANGO_EDAD', 'RANGO_OFERTA', 'RANGO_SUELDO', 'FLG_AAHH', 'ACCION', 'cl_telf1', 'cl_telf2', 'INTENSIDAD_MAX', 'color_final', 'USER_V3', 'campania', 'OFERTA_MAX', 'PLAZO', 'CAPACIDAD_MAX', 'FRESCURA', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'MGNEG', 'GRUPO_TASA', 'TIPO_BASE', 'PROPENSION_IC']

['NUMERO_DOCUMENTO', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'NOMBRES', 'CUOTA', 'tipo_cliente_riegos', 'SALDO_DIFERENCIAL_REENG', 'TIPO_CLIENTE', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'Agencia_comercial', 'Region_comercial', 'GRUPO_MONTO', 'Edad', 'RANGO_EDAD', 'RANGO_OFERTA', 'RANGO_SUELDO', 'FLG_AAHH', 'ACCION', 'cl_telf1', 'cl_telf2', 'INTENSIDAD_MAX', 'color_final', 'USER_V3', 'campania', 'OFERTA_MAX', 'PLAZO', 'CAPACIDAD_MAX', 'FRESCURA', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'MGNEG', 'GRUPO_TASA', 'TIPO_BASE', 'PROPENSION_IC']

In [37]:
df_base.show(3)

+----------------+----------------+--------------------+------------+------+-------------------+-----------------------+-------------+------------+----------------+--------+-----------------+--------------------+---------------+----+----------+------------+------------+------------+--------+---------+---------+--------------+--------------+--------------------+--------+----------+-----+-------------+--------+------+------+------+------+------+------+------+-----+-------------+----------------+-------------+--------+------+-----------------+-----------+--------------+------------+----------+
|NUMERO_DOCUMENTO|APELLIDO_PATERNO|    APELLIDO_MATERNO|     NOMBRES| CUOTA|tipo_cliente_riegos|SALDO_DIFERENCIAL_REENG| TIPO_CLIENTE|DEPARTAMENTO|       PROVINCIA|DISTRITO|Agencia_comercial|    Region_comercial|    GRUPO_MONTO|Edad|RANGO_EDAD|RANGO_OFERTA|RANGO_SUELDO|    FLG_AAHH|  ACCION| cl_telf1| cl_telf2|INTENSIDAD_MAX|   color_final|             USER_V3|campania|OFERTA_MAX|PLAZO|CAPACIDAD_MAX|FRESCURA|Tasa_1|Tasa_2|Tasa_3|Tasa_4|Tasa_5|Tasa_6|Tasa_7|MGNEG|   GRUPO_TASA|       TIPO_BASE|PROPENSION_IC|SERVICIO|RETIRO|MES_DURACION_BASE|Fecha_Envio|      cl_carga|       CRUCE|      lote|
+----------------+----------------+--------------------+------------+------+-------------------+-----------------------+-------------+------------+----------------+--------+-----------------+--------------------+---------------+----+----------+------------+------------+------------+--------+---------+---------+--------------+--------------+--------------------+--------+----------+-----+-------------+--------+------+------+------+------+------+------+------+-----+-------------+----------------+-------------+--------+------+-----------------+-----------+--------------+------------+----------+
|        00001902|           CHOTA|CAMASCA DE COLLANTES|      ESTELA|417.23|       3.NO CLIENTE|                    0.0|     INFORMAL|      LORETO|          MAYNAS| IQUITOS|          IQUITOS|REGION LIMA SUR O...|Disminuye Monto|  75|  60 A MAS|   7000-9999|    930-1500|NO EMERGENTE|BASE TOP|957902557|     NULL|             3|  VERDE OSCURO|            7. Peers|   MUJER|      7800|   36|      458.116|       4|    56|    55|    52|  NULL|  NULL|  NULL|  NULL|    4|Mantiene tasa|SALDO COMPETIDOR|            2|      12|ACTIVO|               09| 2026-09-01|setiembre 2026|BASE REGULAR|NO CLIENTE|
|        00005223|            VEGA|           VELASQUEZ|    HERBERTO| 941.7|       3.NO CLIENTE|                    0.0|  DEPENDIENTE|     UCAYALI|CORONEL PORTILLO|MANANTAY|         PUCALLPA|REGION LIMA SUR O...|   Mejora Monto|  64|  60 A MAS| 15000-19999|   3500-4000|   EMERGENTE|BASE TOP|983108626|999047977|             3|AMARILLO CLARO|10. Dependiente +...| SOLODNI|     15800|   36|      1129.29|       4|    68|    67|    66|    61|    59|    52|  NULL|    4|   Menor tasa|       Blacklist|            4|      12|ACTIVO|               09| 2026-09-01|setiembre 2026|BASE REGULAR|NO CLIENTE|
|        00005710|          CHIONG|    REYNA DE GONZALO|ZOILA AMANDA|1197.9|       3.NO CLIENTE|                    0.0|INDEPENDIENTE|     HUANUCO|         HUANUCO|AMARILIS|          HUANUCO|REGION LIMA SUR O...| Mantiene Monto|  60|  60 A MAS| 25000-29999|   3500-4000|NO EMERGENTE|BASE TOP|976078131|961966061|             1|   VERDE CLARO|            7. Peers|   MUJER|     25000|   36|      2475.37|       4|    51|    50|    49|    47|    46|    43|    39|    2|Mantiene tasa|         Regular|            1|      12|ACTIVO|               09| 2026-09-01|setiembre 2026|BASE REGULAR|NO CLIENTE|
+----------------+----------------+--------------------+------------+------+-------------------+-----------------------+-------------+------------+----------------+--------+-----------------+--------------------+---------------+----+----------+------------+------------+------------+--------+---------+---------+--------------+--------------+--------------------+--------+----------+-----+-------------+--------+------+------+------+------+------+------+------+-----+-------------+----------------+-------------+--------+------+-----------------+-----------+--------------+------------+----------+
only showing top 3 rows

In [38]:
df_base1.show(3)

+----------------+----------------+--------------------+------------+------+-------------------+-----------------------+-------------+------------+----------------+--------+-----------------+--------------------+---------------+----+----------+------------+------------+------------+--------+---------+---------+--------------+--------------+--------------------+--------+----------+-----+-------------+--------+------+------+------+------+------+------+------+-----+-------------+----------------+-------------+--------+------+-----------------+-----------+--------------+------------+----------+
|NUMERO_DOCUMENTO|APELLIDO_PATERNO|    APELLIDO_MATERNO|     NOMBRES| CUOTA|tipo_cliente_riegos|SALDO_DIFERENCIAL_REENG| TIPO_CLIENTE|DEPARTAMENTO|       PROVINCIA|DISTRITO|Agencia_comercial|    Region_comercial|    GRUPO_MONTO|Edad|RANGO_EDAD|RANGO_OFERTA|RANGO_SUELDO|    FLG_AAHH|  ACCION| cl_telf1| cl_telf2|INTENSIDAD_MAX|   color_final|             USER_V3|campania|OFERTA_MAX|PLAZO|CAPACIDAD_MAX|FRESCURA|Tasa_1|Tasa_2|Tasa_3|Tasa_4|Tasa_5|Tasa_6|Tasa_7|MGNEG|   GRUPO_TASA|       TIPO_BASE|PROPENSION_IC|SERVICIO|RETIRO|MES_DURACION_BASE|Fecha_Envio|      cl_carga|       CRUCE|      lote|
+----------------+----------------+--------------------+------------+------+-------------------+-----------------------+-------------+------------+----------------+--------+-----------------+--------------------+---------------+----+----------+------------+------------+------------+--------+---------+---------+--------------+--------------+--------------------+--------+----------+-----+-------------+--------+------+------+------+------+------+------+------+-----+-------------+----------------+-------------+--------+------+-----------------+-----------+--------------+------------+----------+
|        00001902|           CHOTA|CAMASCA DE COLLANTES|      ESTELA|417.23|       3.NO CLIENTE|                    0.0|     INFORMAL|      LORETO|          MAYNAS| IQUITOS|          IQUITOS|REGION LIMA SUR O...|Disminuye Monto|  75|  60 A MAS|   7000-9999|    930-1500|NO EMERGENTE|BASE TOP|957902557|     NULL|             3|  VERDE OSCURO|            7. Peers|   MUJER|      7800|   36|      458.116|       4|    56|    55|    52|  NULL|  NULL|  NULL|  NULL|    4|Mantiene tasa|SALDO COMPETIDOR|            2|      12|ACTIVO|               09| 2026-09-01|setiembre 2026|BASE REGULAR|NO CLIENTE|
|        00005223|            VEGA|           VELASQUEZ|    HERBERTO| 941.7|       3.NO CLIENTE|                    0.0|  DEPENDIENTE|     UCAYALI|CORONEL PORTILLO|MANANTAY|         PUCALLPA|REGION LIMA SUR O...|   Mejora Monto|  64|  60 A MAS| 15000-19999|   3500-4000|   EMERGENTE|BASE TOP|983108626|999047977|             3|AMARILLO CLARO|10. Dependiente +...| SOLODNI|     15800|   36|      1129.29|       4|    68|    67|    66|    61|    59|    52|  NULL|    4|   Menor tasa|       Blacklist|            4|      12|ACTIVO|               09| 2026-09-01|setiembre 2026|BASE REGULAR|NO CLIENTE|
|        00005710|          CHIONG|    REYNA DE GONZALO|ZOILA AMANDA|1197.9|       3.NO CLIENTE|                    0.0|INDEPENDIENTE|     HUANUCO|         HUANUCO|AMARILIS|          HUANUCO|REGION LIMA SUR O...| Mantiene Monto|  60|  60 A MAS| 25000-29999|   3500-4000|NO EMERGENTE|BASE TOP|976078131|961966061|             1|   VERDE CLARO|            7. Peers|   MUJER|     25000|   36|      2475.37|       4|    51|    50|    49|    47|    46|    43|    39|    2|Mantiene tasa|         Regular|            1|      12|ACTIVO|               09| 2026-09-01|setiembre 2026|BASE REGULAR|NO CLIENTE|
+----------------+----------------+--------------------+------------+------+-------------------+-----------------------+-------------+------------+----------------+--------+-----------------+--------------------+---------------+----+----------+------------+------------+------------+--------+---------+---------+--------------+--------------+--------------------+--------+----------+-----+-------------+--------+------+------+------+------+------+------+------+-----+-------------+----------------+-------------+--------+------+-----------------+-----------+--------------+------------+----------+
only showing top 3 rows

In [28]:
print([row['tipo_cliente_riegos' ] for row in df_base.select('tipo_cliente_riegos').distinct().collect()])

['3.NO CLIENTE']

In [6]:
df_base=df_base.withColumn('SERVICIO',F.lit('12'))
df_base=df_base.withColumn('RETIRO',F.lit('ACTIVO'))
df_base=df_base.withColumn('MES_DURACION_BASE',F.lit('09'))
df_base=df_base.withColumn('Fecha_Envio',F.lit('2026-09-01'))
df_base=df_base.withColumn('cl_carga',F.lit('setiembre 2026'))
df_base=df_base.withColumn('CRUCE',F.lit('BASE REGULAR'))
df_base=df_base.withColumn('lote',F.lit('NO CLIENTE'))

In [7]:
from pyspark.sql import functions as F

df_base = df_base.withColumn(
    "Tasa_7",
    F.when(F.col("Tasa_7") == "NULL", None)
     .otherwise(F.col("Tasa_7"))
)

In [8]:
df_base = df_base.replace("NULL", None)

In [9]:
df_base=df_base.filter(F.col('NUMERO_DOCUMENTO').isNotNull())

In [10]:
df_base.count()

180180

In [ ]:
print([row['tipo_cliente_riegos' ] for row in df_base1.select('tipo_cliente_riegos').distinct().collect()])

In [11]:
df_base=df_base.withColumnRenamed('cl_carga','cl_base')

In [13]:
append_table_SQL(spark,df_base,f'Base_Maestra_Alfin_bk_sep',server_kishin,user_kishin,pwd_kishin,'DANTALION')

In [41]:
df_base1_pd=df_base1.toPandas()

In [42]:

ruta_archivo = os.path.join(ruta_csv, 'base_alfin.csv')
df_base1_pd.to_csv(ruta_archivo, sep=';')

In [ ]:
{'DEPARTAMENTO', 'Tasa_6', 'OFERTA_MAX', 'CUOTA', 'GRUPO_TASA', 'tipo_cliente_riegos', 'cl_telf1', 'APELLIDO_PATERNO', 'SALDO_DIFERENCIAL_REENG', 'RANGO_EDAD', 'Tasa_5', 'TIPO_BASE', 'PLAZO', 'PROVINCIA', 'Tasa_7', 'GRUPO_MONTO', 'RANGO_OFERTA', 'USER_V3', 'Agencia_comercial', 'color_final', 'RANGO_SUELDO', 'TIPO_CLIENTE', 'Tasa_3', 'Tasa_4', 'APELLIDO_MATERNO', 'Tasa_1', 'FLG_AAHH', 'CAPACIDAD_MAX', 'Tasa_2', 'cl_telf2', 'Edad', 'NUMERO_DOCUMENTO', 'DISTRITO', 'Region_comercial', 'FRESCURA', 'PROPENSION_IC', 'INTENSIDAD_MAX', 'MGNEG', 'NOMBRES', 'campania'}perf

{'DEPARTAMENTO', 'Tasa_6', 'OFERTA_MAX', 'CUOTA', 'GRUPO_TASA', 'tipo_cliente_riegos', 'cl_telf1', 'APELLIDO_PATERNO', 'SALDO_DIFERENCIAL_REENG', 'RANGO_EDAD', 'Tasa_5', 'TIPO_BASE', 'PLAZO', 'PROVINCIA', 'Tasa_7', 'GRUPO_MONTO', 'RANGO_OFERTA', 'USER_V3', 'Agencia_comercial', 'color_final', 'RANGO_SUELDO', 'TIPO_CLIENTE', 'Tasa_3', 'Tasa_4', 'APELLIDO_MATERNO', 'Tasa_1', 'FLG_AAHH', 'CAPACIDAD_MAX', 'Tasa_2', 'cl_telf2', 'Edad', 'NUMERO_DOCUMENTO', 'DISTRITO', 'Region_comercial', 'FRESCURA', 'PROPENSION_IC', 'INTENSIDAD_MAX', 'MGNEG', 'NOMBRES', 'campania'}

In [ ]:
print(df_base.columns)
print(df_formato.columns)

['PROPENSION_IC', 'USER_V3', 'NUMERO_DOCUMENTO', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'NOMBRES', 'OFERTA_MAX', 'PLAZO', 'CUOTA', 'CAPACIDAD_MAX', 'tipo_cliente_riegos', 'campania', 'SALDO_DIFERENCIAL_REENG', 'TIPO_CLIENTE', 'color_final', 'TIPO_BASE', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'Agencia_comercial', 'Region_comercial', 'GRUPO_TASA', 'GRUPO_MONTO', 'MGNEG', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'Edad', 'RANGO_EDAD', 'RANGO_OFERTA', 'RANGO_SUELDO', 'FRESCURA', 'FLG_AAHH', 'INTENSIDAD_MAX']
['DNI', 'CET', 'CEL1', 'SCORE_TELEFONO']

In [ ]:
['DNI', 'CET', 'CEL1', 'SCORE_TELEFONO']

In [ ]:
df_base_1 = df_base_1.withColumn(
    "address1",
    F.concat_ws(
        " ",
        F.col("X_NOMBRE"),
        F.col("X_APPATERNO"),
        F.col("X_APMATERNO")
    )
)

In [43]:
formato_set=set(df_formato.columns)
base_set=set(df_base.columns)
consulta_campana_set=set(df_validar.columns)

# print(base_set-consulta_campana_set)
# print(consulta_campana_set-base_set)
# print(consulta_campana_set&base_set)
# print(formato_set-consulta_campana_set)
# print(consulta_campana_set-formato_set)
# print(consulta_campana_set&formato_set)

print(base_set-formato_set)

{'VARIACION_OFERTA_CAMPAÑA_ANTERIOR', 'X_APMATERNO', 'VARIACION_TASA_CAMPAÑA_ANTERIOR', 'CAMP_ADP', 'X_NOMBRE', 'tasa_minima', 'X_APPATERNO', 'FLAG_DEUDA_V_OFERTA'}

In [35]:
print(df_base_1.join(df_consulta_campana,['DNI'],'inner').count())
print(df_base_1.join(df_consulta_campana,['DNI'],'left_anti').count())

1
22588

In [ ]:
df_base=df_base.join(df_score,['DNI'],'inner')
df_base_1=df_base_1.join(df_consulta_campana,['DNI'],'inner')
df_base=df_base.dropDuplicates(['DNI'])

In [89]:



print(df_formato.columns)
print(df_base.columns)

['TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'proveedor', 'lote', 'RETIRO', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'SERVICIO', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'PILOTO_PLAZAS', 'INTENSIDAD_MAX', 'marca1', 'marca2', 'marca3', 'AÑO_DURACION_BASE', 'MES_DURACION_BASE', 'FLAT2', 'REP1', 'REP2', 'PILOTO_RETENCION', 'CAMP_BONO', 'ACCION']
['PROPENSION_IC', 'USER_V3', 'NUMERO_DOCUMENTO', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'NOMBRES', 'OFERTA_MAX', 'PLAZO', 'CUOTA', 'CAPACIDAD_MAX', 'tipo_cliente_riegos', 'campania', 'SALDO_DIFERENCIAL_REENG', 'TIPO_CLIENTE', 'color_final', 'TIPO_BASE', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'Agencia_comercial', 'Region_comercial', 'GRUPO_TASA', 'GRUPO_MONTO', 'MGNEG', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'Edad', 'RANGO_EDAD', 'RANGO_OFERTA', 'RANGO_SUELDO', 'FRESCURA', 'FLG_AAHH', 'INTENSIDAD_MAX']

In [ ]:

['TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'proveedor', 'lote', 'RETIRO', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'SERVICIO', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'PILOTO_PLAZAS', 'INTENSIDAD_MAX', 'marca1', 'marca2', 'marca3', 'AÑO_DURACION_BASE', 'MES_DURACION_BASE', 'FLAT2', 'REP1', 'REP2', 'PILOTO_RETENCION', 'CAMP_BONO', 'ACCION']
cl_tel

In [ ]:
df_validar=df_validar.withColumnRenamed('dni','NUMERO_DOCUMENTO')

In [ ]:
print(df_base.columns)

['DNI', 'CET', 'CEL1', 'SCORE_TELEFONO']
['DNI', 'PROPENSION_IC', 'USER_V3', 'X_APPATERNO', 'X_APMATERNO', 'X_NOMBRE', 'OFERTA_MAX', 'tasa_minima', 'PLAZO', 'CUOTA', 'CAPACIDAD_MAX', 'TIPO_CLIENTE_COMERCIAL', 'Campaña', 'SALDO_DIFERENCIAL_REENG', 'TIPO_CLIENTE', 'color_final', 'TIPO_BASE', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'Agencia_comercial', 'REGION_COMERCIAL', 'VARIACION_OFERTA_CAMPAÑA_ANTERIOR', 'VARIACION_TASA_CAMPAÑA_ANTERIOR', 'FLAG_DEUDA_V_OFERTA', 'GRUPO_TASA', 'GRUPO_MONTO', 'MGNEG', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'Edad', 'RANGO_EDAD', 'RANGO_OFERTA', 'RANGO_SUELDO', 'FRESCURA', 'FLG_AAHH', 'INTENSIDAD_MAX', 'CAMP_ADP', 'CET', 'CEL1', 'SCORE_TELEFONO']

In [38]:
formato_set=set(df_formato.columns)
base_set=set(df_base.columns)
consulta_campana_set=set(df_validar.columns)

print(base_set-consulta_campana_set)
print(consulta_campana_set-base_set)
print(consulta_campana_set&base_set)
print(formato_set-consulta_campana_set)
print(consulta_campana_set-formato_set)
print(consulta_campana_set&formato_set)

print(base_set-formato_set)

{'VARIACION_OFERTA_CAMPAÑA_ANTERIOR', 'DEPARTAMENTO', 'VAR_TASA_CREDITO_ANTERIOR', 'FLG_CET_6M', 'X_APPATERNO', 'EXCLUSIVO', 'CUOTA', 'SALDO_DIFERENCIAL_REENG', 'RANGO_EDAD', 'VARIACION_TASA_CAMPAÑA_ANTERIOR', 'X_NOMBRE', 'tasa_minima', 'SUCURSAL_COMERCIAL', 'PROVINCIA', 'RANGO_OFERTA', 'GRUPO_MONTO', 'FLG_AAHH', 'Agencia_comercial', 'RANGO_SUELDO', 'TIPO_CLIENTE', 'Edad', 'X_APMATERNO', 'CAMP_ADP', 'BLOQUE', 'TIPO_CLIENTE_COMERCIAL', 'TIPO_GEST', 'DISTRITO', 'PILOTO_PLAZAS', 'INTENSIDAD_MAX', 'REGION_COMERCIAL'}
{'TASA_6_SS', 'ALERTA_MAQUETA', 'TIPO', 'TASA_2_SS', 'AUTORIZACION_DATOS', 'TASA_1_SS', 'TASA_5_SS', 'TASA_MIN_DESCUENTO', 'FEN', 'TASA_3_SS', 'TASA_7_SS', 'PERFIL_ESPECIAL', 'TASA_4_SS', 'MARCA_PD', 'TOTAL_A_LIQUIDAR', 'rango_deuda', 'COD_USER_V3', 'OFERTA_SS', 'numentidades', 'TASA_CREDITO_ANTERIOR'}
{'Tasa_6', 'OFERTA_MAX', 'GRUPO_TASA', 'FLAG_DEUDA_V_OFERTA', 'Tasa_5', 'TIPO_BASE', 'PLAZO', 'Tasa_7', 'USER_V3', 'color_final', 'Tasa_4', 'Tasa_3', 'Tasa_1', 'CAPACIDAD_MAX', 'Tasa_2', 'PERFIL_RO', 'Campaña', 'DNI', 'FRESCURA', 'PROPENSION_IC', 'MGNEG'}
{'NOMB_BD', 'RETIRO', 'NumEntidades', 'TIPO_DOI', 'CUOTA', 'Tipo_verificacion', 'Prioridad', 'MES_GESTION', 'SCORE_TELEFONO', 'cl_area', 'PROMOCION', 'marca1', 'proveedor', 'cl_telf9', 'RANGO_OFERTA', 'GARANTIA', 'flag_deuda_v_oferta', 'TIPO_CLIENTE', 'color', 'NUEVOS_3M', 'cl_telf2', 'cl_turno', 'cl_telf5', 'TIPO_CONTACTO', 'TIPO_BD', 'cl_fecha_gestion', 'sucursal_comercial', 'segmento', 'fecha_alimentacion', 'incremento_monto_riesgos', 'PILOTO_PLAZAS', 'REP1', 'MEJOR_TIPIFICACION', 'Ubicacion', 'CUOTA_18M', 'Deuda_1', 'ACCION', 'Tasa_12M', 'LEAD_CALIDAD', 'Deuda_3', 'cl_mes', 'Fecha_Envio', 'Entidad_1', 'PERIODO', 'DEPARTAMENTO', 'cl_orden', 'FLAT2', 'cl_accion_ant', 'CUOTA_24M', 'AÑO_DURACION_BASE', 'ID_CLIENTE', 'APELLIDO_PATERNO', 'cl_hits', 'SALDO_DIFERENCIAL_REENG', 'SEGMENTO_USER', 'Oferta_24M', 'Oferta_18M', 'cl_telefono', 'SBI', 'NUEVOS_6M', 'PROVINCIA', 'nombre_base', 'cl_celular', 'Desgravamen_18M', 'cl_accion', 'SERVICIO', 'CUOTA_12M', 'cl_tiempo', 'RETIRO_GEST', 'TASA_VS_MONTO', 'Entidad_3', 'cl_base', 'Region_comercial', 'Desgravamen_12M', 'p_banco', 'cl_telf8', 'OFERTA_FINAL', 'cl_fecha_llamar', 'Tasa_36M', 'Desgravamen_24M', 'cl_carga', 'PERFIL_GLOBAL', 'Oferta_12M', 'PROMOCION2', 'NUM_ENRIQUECIDO', 'REP2', 'BASE', 'cl_predictivo', 'cl_gestion', 'RESULTADO', 'marca3', 'Desgravamen_36M', 'cl_telf7', 'APELLIDO_MATERNO', 'CUOTA_36M', 'Edad', 'PEER', 'CAMP_BONO', 'USUARIO', 'Nombre_prioridad', 'TIPO_GEST', 'Q_VENTAS', 'NUEVOS_9M', 'cl_telf4', 'cl_prioridad', 'cl_telf3', 'LOCALIDAD', 'COD_BD', 'Deuda_2', 'cl_movil', 'GRUPO_TASA_REENGANCHE', 'Tasa_18M', 'Oferta_Minima_Paperless', 'Campana', 'GRUPO_RIESGO', 'PROP_COMER', 'PREST_PREVIO', 'NUEVOS_12M', 'TIENDA', 'CRUCE', 'Desgravamen', 'RETIRO_DESEMBOLSO', 'lote', 'RANGO_EDAD2', 'SUCURSAL', 'tipo_cliente_riegos', 'FECHA_SOL', 'cl_telf1', 'cl_telf10', 'PILOTO_RETENCION', 'cl_base_ant', 'OfertaMaximaSinSeguro', 'RANGO_EDAD', 'PROPENSION', 'cl_hora_gestion', 'GRUPO_MONTO', 'FLG_AAHH', 'Agencia_comercial', 'RANGO_SUELDO', 'STATUS', 'Tasa_24M', 'cl_gestor', 'FEC_NACIMIENTO', 'DESEMBOLSADO', 'NUMERO_DOCUMENTO', 'FLG_DEUDA_PLUS', 'FLAG_REENG', 'MES_DURACION_BASE', 'Entidad_2', 'MONTO_DESEMBOLSADO', 'DISTRITO', 'NUEVOS_4M', 'cl_asesor', 'CLIENTE_NUEVO', 'marca2', 'TEM', 'cl_fecha_ant', 'cl_telf6', 'Validador_Telefono', 'INTENSIDAD_MAX', 'NOMBRES', 'id_carga', 'campania', 'OFERTA_REEN', 'Oferta_36M', 'RANGO_OFERTA2'}
{'TASA_6_SS', 'ALERTA_MAQUETA', 'TIPO', 'TASA_2_SS', 'AUTORIZACION_DATOS', 'FLAG_DEUDA_V_OFERTA', 'TASA_1_SS', 'TASA_5_SS', 'TASA_MIN_DESCUENTO', 'FEN', 'TASA_3_SS', 'TASA_7_SS', 'PERFIL_ESPECIAL', 'TASA_4_SS', 'MARCA_PD', 'TOTAL_A_LIQUIDAR', 'Campaña', 'rango_deuda', 'DNI', 'COD_USER_V3', 'OFERTA_SS', 'numentidades', 'TASA_CREDITO_ANTERIOR'}
{'CAPACIDAD_MAX', 'Tasa_2', 'FRESCURA', 'Tasa_5', 'PROPENSION_IC', 'Tasa_6', 'TIPO_BASE', 'PLAZO', 'Tasa_7', 'MGNEG', 'USER_V3', 'OFERTA_MAX', 'color_final', 'GRUPO_TASA', 'Tasa_4', 'Tasa_3', 'Tasa_1', 'PERFIL_RO'}
{'VARIACION_OFERTA_CAMPAÑA_ANTERIOR', 'Campaña', 'VAR_TASA_CREDITO_ANTERIOR', 'X_APMATERNO', 'DNI', 'VARIACION_TASA_CAMPAÑA_ANTERIOR', 'CAMP_ADP', 'X_NOMBRE', 'tasa_minima', 'FLG_CET_6M', 'X_APPATERNO', 'EXCLUSIVO', 'SUCURSAL_COMERCIAL', 'BLOQUE', 'TIPO_CLIENTE_COMERCIAL', 'FLAG_DEUDA_V_OFERTA', 'REGION_COMERCIAL'}

In [ ]:
{'VARIACION_OFERTA_CAMPAÑA_ANTERIOR', 'DEPARTAMENTO', 'X_APPATERNO', 'CUOTA', 'SCORE_TELEFONO', 'SALDO_DIFERENCIAL_REENG', 'RANGO_EDAD', 'VARIACION_TASA_CAMPAÑA_ANTERIOR', 'X_NOMBRE', 'tasa_minima', 'PROVINCIA', 'RANGO_OFERTA', 'GRUPO_MONTO', 'FLG_AAHH', 'Agencia_comercial', 'CET', 'RANGO_SUELDO', 'TIPO_CLIENTE', 'Edad', 'CEL1', 'X_APMATERNO', 'CAMP_ADP', 'TIPO_CLIENTE_COMERCIAL', 'DISTRITO', 'DNI', 'INTENSIDAD_MAX', 'REGION_COMERCIAL'}
{'TASA_6_SS', 'ALERTA_MAQUETA', 'TIPO', 'TASA_2_SS', 'AUTORIZACION_DATOS', 'TASA_1_SS', 'TASA_5_SS', 'TASA_MIN_DESCUENTO', 'FEN', 'TASA_3_SS', 'TASA_7_SS', 'PERFIL_ESPECIAL', 'TASA_4_SS', 'NUMERO_DOCUMENTO', 'MARCA_PD', 'PERFIL_RO', 'TOTAL_A_LIQUIDAR', 'rango_deuda', 'COD_USER_V3', 'OFERTA_SS', 'numentidades', 'TASA_CREDITO_ANTERIOR'}
{'Tasa_6', 'OFERTA_MAX', 'GRUPO_TASA', 'FLAG_DEUDA_V_OFERTA', 'Tasa_5', 'TIPO_BASE', 'PLAZO', 'Tasa_7', 'USER_V3', 'color_final', 'Tasa_4', 'Tasa_3', 'Tasa_1', 'CAPACIDAD_MAX', 'Tasa_2', 'Campaña', 'FRESCURA', 'PROPENSION_IC', 'MGNEG'}dni

In [ ]:
{'VARIACION_OFERTA_CAMPAÑA_ANTERIOR', 'DEPARTAMENTO', 'Tasa_6', 'X_APPATERNO', 'OFERTA_MAX', 'CUOTA', 'GRUPO_TASA', 'FLAG_DEUDA_V_OFERTA', 'SCORE_TELEFONO', 'SALDO_DIFERENCIAL_REENG', 'RANGO_EDAD', 'VARIACION_TASA_CAMPAÑA_ANTERIOR', 'X_NOMBRE', 'tasa_minima', 'Tasa_5', 'TIPO_BASE', 'PLAZO', 'PROVINCIA', 'Tasa_7', 'GRUPO_MONTO', 'RANGO_OFERTA', 'USER_V3', 'Agencia_comercial', 'color_final', 'RANGO_SUELDO', 'TIPO_CLIENTE', 'Tasa_3', 'Tasa_4', 'Tasa_1', 'FLG_AAHH', 'CET', 'CAPACIDAD_MAX', 'Tasa_2', 'Edad', 'CEL1', 'X_APMATERNO', 'CAMP_ADP', 'TIPO_CLIENTE_COMERCIAL', 'DISTRITO', 'Campaña', 'DNI', 'FRESCURA', 'PROPENSION_IC', 'INTENSIDAD_MAX', 'MGNEG', 'REGION_COMERCIAL'}tasa

{'VARIACION_OFERTA_CAMPAÑA_ANTERIOR', 'DEPARTAMENTO', 'Tasa_6', 'X_APPATERNO', 'OFERTA_MAX', 'CUOTA', 'GRUPO_TASA', 'FLAG_DEUDA_V_OFERTA', 'SCORE_TELEFONO', 'SALDO_DIFERENCIAL_REENG', 'RANGO_EDAD', 'VARIACION_TASA_CAMPAÑA_ANTERIOR', 'X_NOMBRE', 'tasa_minima', 'Tasa_5', 'TIPO_BASE', 'PLAZO', 'PROVINCIA', 'Tasa_7', 'GRUPO_MONTO', 'RANGO_OFERTA', 'USER_V3', 'Agencia_comercial', 'color_final', 'RANGO_SUELDO', 'TIPO_CLIENTE', 'Tasa_3', 'Tasa_4', 'Tasa_1', 'FLG_AAHH', 'CET', 'CAPACIDAD_MAX', 'Tasa_2', 'Edad', 'CEL1', 'X_APMATERNO', 'CAMP_ADP', 'TIPO_CLIENTE_COMERCIAL', 'DISTRITO', 'Campaña', 'DNI', 'FRESCURA', 'PROPENSION_IC', 'INTENSIDAD_MAX', 'MGNEG', 'REGION_COMERCIAL'}

In [ ]:
{'TASA_6_SS', 'ALERTA_MAQUETA', 'Tasa_6', 'TASA_2_SS', 'TIPO', 'AUTORIZACION_DATOS', 'OFERTA_MAX', 'GRUPO_TASA', 'FLAG_DEUDA_V_OFERTA', 'TASA_1_SS', 'TASA_5_SS', 'PROPENSION_DISTRIBUCION', 'TASA_MIN_DESCUENTO', 'FEN', 'Tasa_5', 'TIPO_BASE', 'PLAZO', 'Tasa_7', 'COLOR_FINAL', 'USER_V3', 'Tasa_4', 'Tasa_3', 'Tasa_1', 'TASA_3_SS', 'TASA_7_SS', 'CAPACIDAD_MAX', 'Tasa_2', 'PERFIL_ESPECIAL', 'TASA_4_SS', 'NUMERO_DOCUMENTO', 'MARCA_PD', 'TOTAL_A_LIQUIDAR', 'PERFIL_RO', 'Campaña', 'rango_deuda', 'FRESCURA', 'COD_USER_V3', 'OFERTA_SS', 'MGNEG', 'numentidades', 'TASA_CREDITO_ANTERIOR'}fres

{'TASA_6_SS', 'ALERTA_MAQUETA', 'Tasa_6', 'TASA_2_SS', 'TIPO', 'AUTORIZACION_DATOS', 'OFERTA_MAX', 'GRUPO_TASA', 'FLAG_DEUDA_V_OFERTA', 'TASA_1_SS', 'TASA_5_SS', 'PROPENSION_DISTRIBUCION', 'TASA_MIN_DESCUENTO', 'FEN', 'Tasa_5', 'TIPO_BASE', 'PLAZO', 'Tasa_7', 'COLOR_FINAL', 'USER_V3', 'Tasa_4', 'Tasa_3', 'Tasa_1', 'TASA_3_SS', 'TASA_7_SS', 'CAPACIDAD_MAX', 'Tasa_2', 'PERFIL_ESPECIAL', 'TASA_4_SS', 'NUMERO_DOCUMENTO', 'MARCA_PD', 'TOTAL_A_LIQUIDAR', 'PERFIL_RO', 'Campaña', 'rango_deuda', 'FRESCURA', 'COD_USER_V3', 'OFERTA_SS', 'MGNEG', 'numentidades', 'TASA_CREDITO_ANTERIOR'}

In [ ]:
df_base=df_base.select('DNI','X_APPATERNO', 'X_APMATERNO', 'X_NOMBRE','color_final','Agencia_comercial','CET','OFERTA_MAX','USER_V3')

In [ ]:
['PROPENSION_IC', 'USER_V3', 'DNI', 'X_APPATERNO', 'X_APMATERNO', 'X_NOMBRE', 'OFERTA_MAX', 'tasa_minima', 'PLAZO', 'CUOTA', 'CAPACIDAD_MAX', 'TIPO_GEST', 'TIPO_CLIENTE_COMERCIAL', 'Campaña', 'SALDO_DIFERENCIAL_REENG', 'TIPO_CLIENTE', 'color_final', 'PERFIL_RO', 'TIPO_BASE', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'SUCURSAL_COMERCIAL', 'Agencia_comercial', 'REGION_COMERCIAL', 'VARIACION_OFERTA_CAMPAÑA_ANTERIOR', 'VARIACION_TASA_CAMPAÑA_ANTERIOR', 'VAR_TASA_CREDITO_ANTERIOR', 'FLG_CET_6M', 'FLAG_DEUDA_V_OFERTA', 'GRUPO_TASA', 'GRUPO_MONTO', 'MGNEG', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'Edad', 'RANGO_EDAD', 'RANGO_OFERTA', 'RANGO_SUELDO', 'BLOQUE', 'FRESCURA', 'FLG_AAHH', 'INTENSIDAD_MAX', 'PILOTO_PLAZAS', 'CAMP_ADP', 'EXCLUSIVO']

In [ ]:

query = f"""
	SELECT dni_cliente as Dni,'1' as ref
    FROM Alice.prospectos_correos_alfin 
    where fecha_registro>='2026-08-01'
"""
df_correo_ref = pd.read_sql(query, engine_mysql)

ruta_archivo = os.path.join(ruta_alfin, 'envio_subir.csv')
df_correo_ref.to_csv(ruta_archivo, sep=',')

filename='BASE_TARGET_20260827.csv'

df_correo_01=cargar_archivo_csv_ruta(spark,filename,',',True,ruta_alfin)

In [8]:
query = """
    select *,NUMERO_DOCUMENTO as Dni   
    from DANTALION.dbo.Base_Maestra_ALFIN_BK
    where cl_telf1 is not null
    and fecha_envio>='2026-08-01'
    AND RETIRO = 'ACTIVO'
    and cruce='CET'
    """
df_formato=obtener_tabla_sql(spark,query,server_kishin,user_kishin,pwd_kishin,db_kishin)

query = """
	SELECT distinct Dni FROM THOTH.dbo.Tmp_LLamadas_Alfin_5 
    where Descripcion_ in(
        'EXPRESO FUTURA DENUNCIA ANTE INDECOPI O REGULADOR',
        'EXPRESO QUE NO AUTORIZÓ USO DE DATOS PERSONALES',
        'EXPRESO RECIBIR MÚLTIPLES LLAMADAS',
        'FUERA DE SERVICIO'
    )
    """
df_quitar=obtener_tabla_sql(spark,query,server_zeus,user_zeus,pwd_zeus,db_zeus)

query = """
    SELECT Dni FROM THOTH.dbo.Tmp_LLamadas_Alfin_5 
    where Numero_Campana='401'
    and list_description<>'provicional'
    """
df_quitar2=obtener_tabla_sql(spark,query,server_zeus,user_zeus,pwd_zeus,db_zeus)

print(df_formato.count())
print(df_quitar.count())
print(df_quitar2.count())

23174
1479
664

In [9]:
df_formato=df_formato.join(df_quitar, ['Dni'], "left_anti")
df_formato=df_formato.join(df_quitar2, ['Dni'], "left_anti")

In [10]:
print(df_formato.count())

df_formato=df_formato.join(df_correo_01, ['Dni'], "left_anti")
print(df_formato.count())

23039
8439

In [ ]:
['Dni', 'TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'proveedor', 'lote', 'RETIRO', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'SERVICIO', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'PILOTO_PLAZAS', 'INTENSIDAD_MAX', 'marca1', 'marca2', 'marca3', 'AÑO_DURACION_BASE', 'MES_DURACION_BASE', 'FLAT2', 'REP1', 'REP2', 'PILOTO_RETENCION', 'CAMP_BONO', 'ACCION']colo

['Dni', 'TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'proveedor', 'lote', 'RETIRO', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'SERVICIO', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'PILOTO_PLAZAS', 'INTENSIDAD_MAX', 'marca1', 'marca2', 'marca3', 'AÑO_DURACION_BASE', 'MES_DURACION_BASE', 'FLAT2', 'REP1', 'REP2', 'PILOTO_RETENCION', 'CAMP_BONO', 'ACCION']

In [11]:
df_formato=df_formato.filter(F.col('OFERTA_MAX')>=5000)

In [14]:
df_formato=df_formato.filter(~F.col('USER_V3').isin('7. Peers','4. MES + PLD No Peers','2. sunedu & sunarp B','1. sunedu & sunarp A'))

In [16]:
df_formato.groupBy('color_final') \
    .count() \
    .orderBy('color_final') \
    .show(30)

+---------------+-----+
|    color_final|count|
+---------------+-----+
| AMARILLO CLARO|  856|
|AMARILLO OSCURO| 1568|
|  NARANJA CLARO|  511|
| NARANJA OSCURO|  460|
|    VERDE CLARO|  343|
|   VERDE OSCURO|  612|
+---------------+-----+

In [ ]:
df_formato=df_formato.filter(F.col('OFERTA_MAX')>=5000)

In [20]:
df_formato=df_formato.filter(F.col('color_final').isin('VERDE OSCURO','VERDE CLARO','','AMARILLO OSCURO'))

In [ ]:
df_formato=df_formato.filter(~F.col('USER_V3').isin('7. Peers','4. MES + PLD No Peers','2. sunedu & sunarp B','1. sunedu & sunarp A'))

In [4]:
df_f=cargar_archivo_csv_ruta(spark,'validar_campana_alfin_bloqueo.csv',';',True,ruta_alfin)

In [6]:
print(df_f.columns)

['DNI', '_c0', 'CLIENTE', 'CELULAR', 'AGENCIA', 'MONTO', 'COLOR_FINAL', 'COD_USER_V3', 'USER_V3', 'PERFIL_RO', 'campaña', 'OFERTA_MAX', 'PLAZO', 'CAPACIDAD_MAX', 'FRESCURA', 'rango_deuda', 'numentidades', 'TOTAL_A_LIQUIDAR', 'TASA_CREDITO_ANTERIOR', 'TASA_1', 'TASA_2', 'TASA_3', 'TASA_4', 'TASA_5', 'TASA_6', 'TASA_7', 'MGNEG', 'MARCA_PD', 'AUTORIZACION_DATOS', 'FLAG_DEUDA_V_OFERTA', 'GRUPO_TASA', 'TIPO_BASE', 'PROPENSION_DISTRIBUCION', 'OFERTA_SS', 'TASA_1_SS', 'TASA_2_SS', 'TASA_3_SS', 'TASA_4_SS', 'TASA_5_SS', 'TASA_6_SS', 'TASA_7_SS', 'ALERTA_MAQUETA', 'FEN', 'PERFIL_ESPECIAL', 'TASA_MIN_DESCUENTO', 'TIPO']

In [ ]:
['DNI', '_c0', 'CLIENTE', 'CELULAR', 'AGENCIA', 'MONTO', 'COLOR_FINAL', 'COD_USER_V3', 'USER_V3', 'PERFIL_RO', 'campaña', 'OFERTA_MAX', 'PLAZO', 'CAPACIDAD_MAX', 'FRESCURA', 'rango_deuda', 'numentidades', 'TOTAL_A_LIQUIDAR', 'TASA_CREDITO_ANTERIOR', 'TASA_1', 'TASA_2', 'TASA_3', 'TASA_4', 'TASA_5', 'TASA_6', 'TASA_7', 'MGNEG', 'MARCA_PD', 'AUTORIZACION_DATOS', 'FLAG_DEUDA_V_OFERTA', 'GRUPO_TASA', 'TIPO_BASE', 'PROPENSION_DISTRIBUCION', 'OFERTA_SS', 'TASA_1_SS', 'TASA_2_SS', 'TASA_3_SS', 'TASA_4_SS', 'TASA_5_SS', 'TASA_6_SS', 'TASA_7_SS', 'ALERTA_MAQUETA', 'FEN', 'PERFIL_ESPECIAL', 'TASA_MIN_DESCUENTO', 'TIPO']ce

In [7]:
df_formato_pd=df_f.select(F.col('DNI').alias('dni_cliente'),
F.col('COLOR_FINAL').alias('color'),
F.col('AGENCIA').alias('agencia_atencion'),
F.col('CELULAR').alias('celular'),
F.col('CELULAR').alias('telefono_cliente'),
F.col('OFERTA_MAX').alias('monto_solicitado'),
F.col('CLIENTE').alias('nombre_cliente')).toPandas()

c:\Users\Data\Documents\lazo_fernando\target_script_01\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()
c:\Users\Data\Documents\lazo_fernando\target_script_01\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:348: UserWarning: toPandas attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  [PACKAGE_NOT_INSTALLED] PyArrow >= 18.0.0 must be installed; however, it was not found.
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warn(msg)

In [21]:
df_formato_pd=df_formato.select(F.col('NUMERO_DOCUMENTO').alias('dni_cliente'),
F.col('color_final').alias('color'),
F.col('Agencia_comercial').alias('agencia_atencion'),
F.col('cl_telf1').alias('celular'),
F.col('cl_telf1').alias('telefono_cliente'),
F.col('OFERTA_MAX').alias('monto_solicitado'),
F.col('NOMBRES').alias('nombre_cliente')).toPandas()

c:\Users\Data\Documents\lazo_fernando\target_script_01\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()
c:\Users\Data\Documents\lazo_fernando\target_script_01\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:348: UserWarning: toPandas attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  [PACKAGE_NOT_INSTALLED] PyArrow >= 18.0.0 must be installed; however, it was not found.
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warn(msg)

In [8]:
df_formato_pd['dni_vendedor']='BOT'
df_formato_pd['cdv_alfin_banco']='ROSA HONOR'
df_formato_pd['canal_campo']='CALL CENTER / TARGET OUTSOURCING'
df_formato_pd['codigo_ejecutivo_id']='BOT'
df_formato_pd['ejecutivo_target']='00000001'
df_formato_pd['operador']='TARGET'
df_formato_pd['tipo_gestion']='Derivacion'
df_formato_pd['tipo_carga']='MANUAL'
df_formato_pd['supervisor']='CARLOS ENRIQUE RAMIREZ CACHIQUE'

In [9]:
fechas = pd.to_datetime([
    "2026-08-28",
    "2026-08-31",
    "2026-08-29",
])

df_formato_pd["fecha_visita"] = np.random.choice(
    fechas,
    size=len(df_formato_pd)
)

horas = np.random.randint(9, 19, size=len(df_formato_pd))

minutos = np.random.choice([0, 15, 30, 45], size=len(df_formato_pd))

df_formato_pd["hora_visita"] = [
    f"{h:02d}:{m:02d}:00"
    for h, m in zip(horas, minutos)
]

In [10]:
query = f"""
	select *,agencia_correo as agencia_atencion ,agencia_Formulario as agencia_tienda from Alice.agencias_alfin
"""
df_agencia = pd.read_sql(query, engine_mysql)
df_agencia.drop_duplicates(subset=["agencia_atencion"], inplace=True)

df_agencia["agencia_atencion"] = df_agencia["agencia_atencion"].str.strip()
df_formato_pd["agencia_atencion"] = df_formato_pd["agencia_atencion"].str.strip()



equivalencias = {
    'SAN JUAN DE LURIG': 'SAN JUAN DE LURIGANCHO',
    'ENMANCIPACION': 'EMANCIPACION',
    'PC HUANCAYO': 'HUANCAYO',
    'PC TACNA': 'TACNA',
    'PC HUARAZ': 'HUARAZ',
    'TRUJ CENTRO': 'TRUJILLO CENTRO',
    'TRUJ AMERICA': 'TRUJILLO AMERICA',
    'AREQ CAYMA': 'AREQUIPA CAYMA',
    'AREQ PAMPILLA': 'AREQUIPA PAMPILLA'
}

df_formato_pd['agencia_atencion'] = (
    df_formato_pd['agencia_atencion']
    .replace(equivalencias)
)
# df_formato_pd.drop_duplicates(subset=["dni"], inplace=True)



set_correo = set(
    df_formato_pd['agencia_atencion']
    .dropna()
    .drop_duplicates()
)

set_agencia = set(
    df_agencia['agencia_atencion']
    .dropna()
    .drop_duplicates()
)
# print(set_correo & set_agencia)
print(set_agencia - set_correo)
print(set_correo -set_agencia )

set()
set()

In [11]:
df_formato_pd=df_formato_pd.merge(df_agencia, on='agencia_atencion', how='left')

In [12]:
df_correo=df_formato_pd[['canal_campo', 'supervisor', 'ejecutivo_target', 'codigo_ejecutivo_id', 'cdv_alfin_banco', 'dni_cliente', 'nombre_cliente', 'monto_solicitado', 'celular', 'agencia_atencion', 'fecha_visita','hora_visita','color']] .copy()

df_formulario=df_formato_pd[['dni_vendedor', 'operador', 'dni_cliente', 'nombre_cliente', 'telefono_cliente', 'agencia_tienda', 'fecha_visita', 'monto_solicitado', 'tipo_gestion']].copy()

display(df_correo.head(2))
display(df_formulario.head(2))

,canal_campo,supervisor,ejecutivo_target,codigo_ejecutivo_id,cdv_alfin_banco,dni_cliente,nombre_cliente,monto_solicitado,celular,agencia_atencion,fecha_visita,hora_visita,color
0,CALL CENTER / TARGET OUTSOURCING,CARLOS ENRIQUE RAMIREZ CACHIQUE,00000001,BOT,ROSA HONOR,25180454,ISAC HUANCA CHURA,14200,991359730,CUSCO LA CULTURA,2026-08-28,13:30:00,VERDE CLARO
1,CALL CENTER / TARGET OUTSOURCING,CARLOS ENRIQUE RAMIREZ CACHIQUE,00000001,BOT,ROSA HONOR,25180454,ISAC HUANCA CHURA,14200,991359730,CUSCO LA CULTURA,2026-08-29,14:00:00,VERDE CLARO

,dni_vendedor,operador,dni_cliente,nombre_cliente,telefono_cliente,agencia_tienda,fecha_visita,monto_solicitado,tipo_gestion
0,BOT,TARGET,25180454,ISAC HUANCA CHURA,991359730,734299 - CUSCO LA CULTURA,2026-08-28,14200,Derivacion
1,BOT,TARGET,25180454,ISAC HUANCA CHURA,991359730,734299 - CUSCO LA CULTURA,2026-08-29,14200,Derivacion

In [13]:
filename='TARGET.txt'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_target_desembolso = pd.read_csv(ruta_archivo,sep='|')
df_target_desembolso = df_target_desembolso[['DNI']].copy()
df_target_desembolso['CANAL']='CANAL'
filename='ACUM_DESEM.txt'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_fugas = pd.read_csv(ruta_archivo,sep='|')
df_fugas = df_fugas[['DNI','CANALVENTA']].copy()
df_target_desembolso['DNI'] = (
    df_target_desembolso['DNI']
    .astype(str)
    .str.replace(r'\D', '', regex=True)   
    .replace('', pd.NA)                     
    .str.zfill(8)                           
)
df_fugas['DNI'] = (
    df_fugas['DNI']
    .astype(str)
    .str.replace(r'\D', '', regex=True)   
    .replace('', pd.NA)                     
    .str.zfill(8)                           
)

df_desembolso=df_fugas.merge(
    df_target_desembolso,
    on=['DNI'],
    how='left'
)
df_desembolso = df_desembolso.fillna("OTROS")
df_desembolso.rename(columns={'DNI': 'dni_cliente'}, inplace=True)


filename='RetiroDefinitivo_BlackList.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_def_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_BlackList.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_Telefonos.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_telf = pd.read_csv(ruta_archivo,sep='|')
filename='retiro_correo_alfin.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_retiro_correo = pd.read_csv(ruta_archivo,sep=',')

# filename='desembolso.csv'
# ruta_archivo = os.path.join(ruta_alfin, filename)
# df_des = pd.read_csv(ruta_archivo,sep=';')

df_def_blacklist = df_def_blacklist.rename(columns={'DNI': 'dni_cliente'})
df_blacklist = df_blacklist.rename(columns={'DNI': 'dni_cliente'})
df_telf= df_telf.rename(columns={'TELEFONO': 'celular'})
df_retiro_correo= df_retiro_correo.rename(columns={'DNI': 'dni_cliente'})

# Blacklists de DNI
# df6 = df_des.copy()
# df6["celular"] = None
# df6 = df6[["dni_cliente", "celular"]]

# Blacklists de DNI
df1 = df_def_blacklist.copy()
df1["celular"] = None
df1 = df1[["dni_cliente", "celular"]]

df2 = df_blacklist.copy()
df2["celular"] = None
df2 = df2[["dni_cliente", "celular"]]

# Blacklist de teléfonos
df3 = df_telf.copy()
df3["dni_cliente"] = None
df3 = df3[["dni_cliente", "celular"]]

# Archivo con DNI y celular
df4 = df_retiro_correo[["dni_cliente", "celular"]].copy()

# Unir todo
df_retiros = pd.concat(
    [df1, df2, df3, df4],
    ignore_index=True
)




dni_retiro = set(df_retiros['dni_cliente'].dropna())
cel_retiro = set(df_retiros['celular'].dropna())
dni_desembolso = set(df_desembolso['dni_cliente'].dropna())

In [14]:
df_formato_pd=df_formato_pd[
    ~df_formato_pd['dni_cliente'].isin(dni_retiro)&
    ~df_formato_pd['celular'].isin(cel_retiro)&
    ~df_formato_pd['dni_cliente'].isin(dni_desembolso)
    ].copy()
df_formato_pd.shape

(3093, 24)

In [15]:

df_correo.to_sql(
    name="prospectos_correos_alfin",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

df_formulario.to_sql(
    name="prospectos_envio_alfin",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

3100