In [ ]:
import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *

spark = SparkSession.builder \
    .appName("SparkExample") \
    .master("local[*]") \
    .config('spark.driver.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.2.1.jre11.jar') \
    .config('spark.executor.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.2.1.jre11.jar') \
    .config('spark.executor.memory', '8g') \
    .config('spark.driver.memory', '8g') \
    .getOrCreate()

In [11]:


engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

query = """
select ll_dni, ll_numero, ll_accion, ll_fecha, ll_ini_registro, ll_fin_registro, ll_hora, ll_duracion, ll_fecha_llamar, ll_gestor, ll_tipo_telefono, ll_base, ll_mes,  ll_cid, lead_id , campana from crm_target.alfcc_llamadas
where ll_fecha='2026-05-19'
limit 10
"""

df_formato = pd.read_sql(query, engine_mysql)

# df_dni["dni_cliente"] = (
#     df_dni["dni_cliente"]
#     .astype(str)
#     .str.zfill(8)
# )
df_formato.head()

,ll_dni,ll_numero,ll_accion,ll_fecha,ll_ini_registro,ll_fin_registro,ll_hora,ll_duracion,ll_fecha_llamar,ll_gestor,ll_tipo_telefono,ll_base,ll_mes,ll_cid,lead_id,campana
0,47963933,974701119,97,2026-05-19,2026-05-19 09:01:30,2026-05-19 09:01:50,9,20,None,606,2,Mayo 2026,Mayo 2026,3574963,12687539,ALFCC
1,80275454,920369536,79,2026-05-19,2026-05-19 09:01:31,2026-05-19 09:02:54,9,83,None,719,2,Mayo 2026,Mayo 2026,3518916,12688821,ALFCC
2,45302009,987958498,97,2026-05-19,2026-05-19 09:01:25,2026-05-19 09:02:58,9,93,None,370,2,Mayo 2026,Mayo 2026,3492077,12692595,ALFCC
3,40246315,949583354,79,2026-05-19,2026-05-19 09:01:54,2026-05-19 09:03:13,9,79,None,606,2,Mayo 2026,Mayo 2026,3468892,12690958,ALFCC
4,70324617,941814184,97,2026-05-19,2026-05-19 09:02:53,2026-05-19 09:03:19,9,26,None,265,2,Mayo 2026,Mayo 2026,3513597,12687864,ALFCC

In [8]:
df_formato.head()

,ll_dni,ll_numero,ll_accion,ll_fecha,ll_ini_registro,ll_fin_registro,ll_hora,ll_duracion,ll_fecha_llamar,ll_gestor,ll_tipo_telefono,ll_base,ll_mes,ll_area,ll_cid,lead_id,uniqueid,call_id,interesado,campana
0,47963933,974701119,97,2026-05-19,2026-05-19 09:01:30,2026-05-19 09:01:50,9,20,None,606,2,Mayo 2026,Mayo 2026,0,3574963,12687539,1779199270.62,V5190901090012687539,None,ALFCC
1,80275454,920369536,79,2026-05-19,2026-05-19 09:01:31,2026-05-19 09:02:54,9,83,None,719,2,Mayo 2026,Mayo 2026,0,3518916,12688821,1779199264.43,V5190901040012688821,None,ALFCC
2,45302009,987958498,97,2026-05-19,2026-05-19 09:01:25,2026-05-19 09:02:58,9,93,None,370,2,Mayo 2026,Mayo 2026,0,3492077,12692595,1779199264.35,V5190901040012692595,None,ALFCC
3,40246315,949583354,79,2026-05-19,2026-05-19 09:01:54,2026-05-19 09:03:13,9,79,None,606,2,Mayo 2026,Mayo 2026,0,3468892,12690958,1779199283.95,V5190901220012690958,None,ALFCC
4,70324617,941814184,97,2026-05-19,2026-05-19 09:02:53,2026-05-19 09:03:19,9,26,None,265,2,Mayo 2026,Mayo 2026,0,3513597,12687864,1779199359.174,V5190902390012687864,None,ALFCC

In [6]:

filename='CRE 16.05.5.csv'
df_bot=cargar_archivo_csv(spark,filename,',',True)
df_bot.show(2,truncate=False)

+------+---------------------------+---------+------------+-------------------+-------------------------+-------------------------+--------------+---------+------------------------------------------------------------------------------------------------------+-------------+-----------+--------------+------+-------+-----+----+--------+-------+---------+------+------+---------+-----------+-----------------+---------------+--------------+---------+-------+-----------------+----+------------+---------+--------+-------------------------------------------+----------------+---------------+--------------+-------------+-------------------------+--------------------+---------+--------+
|Codigo|Contacto                   |Telefono |Tipificacion|Estado             |Fecha Inicio             |Fecha Fin                |Duracion (seg)|Grabacion|ruta_descarga                                                                                         |Se envio link|Lista negra|Grupo familiar|TIENDA|AGENCIA|FECHA|HORA|cl_carga|cl_id  |cl_telf2 |Region|PERFIL|cl_base  |Semaforo   |MARCA_PD         |LOTE           |GRUPO_SEGMENTO|FLG_PEARS|FLG_URB|SITUACION_LABORAL|MSI |DEPARTAMENTO|PROVINCIA|DISTRITO|DIRECCION                                  |OFERTA_CREDICASH|PLAZO_CREDICASH|TASA_CREDICASH|CME_CREDICASH|PRODUCTO_EXTERNO         |PROPENSION_CREDICASH|TIPO_ZONA|FRESCURA|
+------+---------------------------+---------+------------+-------------------+-------------------------+-------------------------+--------------+---------+------------------------------------------------------------------------------------------------------+-------------+-----------+--------------+------+-------+-----+----+--------+-------+---------+------+------+---------+-----------+-----------------+---------------+--------------+---------+-------+-----------------+----+------------+---------+--------+-------------------------------------------+----------------+---------------+--------------+-------------+-------------------------+--------------------+---------+--------+
|32455 |ELIZABETH MAMANI CHOQUECOTA|971761534|Contestadora|Buzón / No contesto|18/05/2026 12:11:40 p. m.|-                        |-             |No       |NULL                                                                                                  |No           |No         |-             |NULL  |NULL   |NULL |NULL|46143   |3575777|0        |R7    |D1    |Mayo 2026|02 FLEXIBLE|NO MES, PLD PEERS|BASE 2026-05-01|R             |1        |0      |DEPENDIENTE      |NULL|MOQUEGUA    |ILO      |ILO     |VISTA AL MAR MZ-143 LOTE-9                 |11000           |36             |36.3000       |812.1400     |CREDICASH R / ELECTRO MSI|1                   |3. URB   |4       |
|32454 |SUSANA PARANCO ARIZACA     |989045856|NULL        |Completado         |18/05/2026 12:11:32 p. m.|18/05/2026 12:14:51 p. m.|195           |Si       |https://aiyou-uploads.s3.us-east-1.amazonaws.com/app/8/llamadas/2026-05-18/llamadas_20260518121452.mp3|No           |No         |-             |NULL  |NULL   |NULL |NULL|46143   |3567127|986702979|R7    |D0    |Mayo 2026|02 FLEXIBLE|MES, PLD PEERS   |BASE 2026-05-01|R             |0        |0      |INFORMAL         |NULL|MOQUEGUA    |ILO      |ILO     |CP SANTA ROSA DE YANAQUE SECTOR CHALLAPAMPA|5600            |36             |35.2000       |794.3500     |CREDICASH R / ELECTRO MSI|1                   |3. URB   |4       |
+------+---------------------------+---------+------------+-------------------+-------------------------+-------------------------+--------------+---------+------------------------------------------------------------------------------------------------------+-------------+-----------+--------------+------+-------+-----+----+--------+-------+---------+------+------+---------+-----------+-----------------+---------------+--------------+---------+-------+-----------------+----+------------+---------+--------+-------------------------------------------+----------------+---------------+--------------+-------------+-------------------------+--------------------+---------+--------+
only showing top 2 rows

In [ ]:
import os

ruta_archivos = ruta_csv

archivos_cre = [

    archivo

    for archivo in os.listdir(ruta_archivos)

    if archivo.startswith('CRE ')
    and archivo.endswith('.csv')
]

In [ ]:
dfs = []

for filename in archivos_cre:

    print(f"Leyendo: {filename}")

    df_tmp = cargar_archivo_csv(
        spark,
        filename,
        ',',
        True
    )

    dfs.append(df_tmp)

Leyendo: CRE 16.05.1.csv
Leyendo: CRE 16.05.2.csv
Leyendo: CRE 16.05.3.csv
Leyendo: CRE 16.05.4.csv
Leyendo: CRE 16.05.5.csv
Leyendo: CRE 16.05.6.csv
Leyendo: CRE 16.05.7.csv
Leyendo: CRE 16.05.8.csv
Leyendo: CRE 18.05.1.csv
Leyendo: CRE 18.05.2.csv
Leyendo: CRE 18.05.3.csv
Leyendo: CRE 18.05.4.csv

In [ ]:
from functools import reduce

df_bot = reduce(
    lambda df1, df2: df1.unionByName(df2),
    dfs
)

In [ ]:
df_bot.count()

32276

In [ ]:
from pyspark.sql import functions as F

df_bot = df_bot.withColumn(

    'Duracion (seg)',

    F.when(
        F.col('Duracion (seg)') == '-',
        None
    ).otherwise(
        F.col('Duracion (seg)')
    ).cast('int')
)

In [ ]:
df_formato[['ll_dni', 'll_numero', 'll_accion', 'll_fecha', 'll_ini_registro', 'll_fin_registro', 'll_hora', 'll_duracion', 'll_fecha_llamar', 'll_gestor', 'll_tipo_telefono', 'll_base', 'll_mes', 'll_area', 'll_cid', 'lead_id', 'uniqueid', 'call_id', 'interesado', 'accion_ant', 'auditor', 'resultado_auditoria', 'fecha_auditoria', 'comentario_auditor', 'accion_nueva', 'autorizacion', 'campana']].head()

,ll_dni,ll_numero,ll_accion,ll_fecha,ll_ini_registro,ll_fin_registro,ll_hora,ll_duracion,ll_fecha_llamar,ll_gestor,ll_tipo_telefono,ll_base,ll_mes,ll_area,ll_cid
0,,900005806,28,2025-08-20,2025-08-20 11:46:51,2025-08-20 11:47:12,11,21,NaT,1,2,Agosto 2025,Agosto 2025,0,5
1,73873031,900005806,3,2025-08-20,2025-08-20 18:58:32,2025-08-20 19:01:29,18,177,NaT,1,2,Agosto 2025,Agosto 2025,0,5
2,47169117,900000088,3,2025-08-29,2025-08-29 12:55:42,2025-08-29 12:58:06,12,144,NaT,1,2,Agosto 2025,Agosto 2025,0,1
3,47757398,900010886,3,2025-08-29,2025-08-29 12:59:56,2025-08-29 13:00:24,12,28,NaT,1,2,Agosto 2025,Agosto 2025,0,13
4,43781495,900011694,3,2025-08-29,2025-08-29 13:06:01,2025-08-29 13:06:25,13,24,NaT,1,2,Agosto 2025,Agosto 2025,0,14

In [11]:
df_bot.show(10)

+------+--------------------+---------+--------------------+-------------------+--------------------+--------------------+--------------+---------+--------------------+-------------+-----------+--------------+------+-------+-----+----+--------+-------+---------+------+------+---------+-------------------+--------------------+---------------+--------------+---------+-------+-----------------+----+-------------+---------+--------------------+--------------------+----------------+---------------+--------------+-------------+--------------------+--------------------+---------+--------+
|Codigo|            Contacto| Telefono|        Tipificacion|             Estado|        Fecha Inicio|           Fecha Fin|Duracion (seg)|Grabacion|       ruta_descarga|Se envio link|Lista negra|Grupo familiar|TIENDA|AGENCIA|FECHA|HORA|cl_carga|  cl_id| cl_telf2|Region|PERFIL|  cl_base|           Semaforo|            MARCA_PD|           LOTE|GRUPO_SEGMENTO|FLG_PEARS|FLG_URB|SITUACION_LABORAL| MSI| DEPARTAMENTO|PROVINCIA|            DISTRITO|           DIRECCION|OFERTA_CREDICASH|PLAZO_CREDICASH|TASA_CREDICASH|CME_CREDICASH|    PRODUCTO_EXTERNO|PROPENSION_CREDICASH|TIPO_ZONA|FRESCURA|
+------+--------------------+---------+--------------------+-------------------+--------------------+--------------------+--------------+---------+--------------------+-------------+-----------+--------------+------+-------+-----+----+--------+-------+---------+------+------+---------+-------------------+--------------------+---------------+--------------+---------+-------+-----------------+----+-------------+---------+--------------------+--------------------+----------------+---------------+--------------+-------------+--------------------+--------------------+---------+--------+
| 22351|DEMETRIO CHOQUEPA...|994486412|NO CONTACTO > NO ...|         Completado|16/05/2026 02:54:...|16/05/2026 02:54:...|             6|       Si|https://aiyou-upl...|           No|         No|             -|  NULL|   NULL| NULL|NULL|   46143|3539361|        0|    R7|    D0|Mayo 2026|  01 SUPER FLEXIBLE|   MES, PLD NO PEERS|BASE 2026-05-01|             R|        0|      0|      DEPENDIENTE|NULL|     AREQUIPA| AREQUIPA|      CERRO COLORADO|AVMARIANO MELGAR ...|           15000|             36|       33.6000|    1815.9400|CREDICASH R / ELE...|                   1|   3. URB|       4|
| 22352| DORA HUISA LLICAHUA|974423195|NO CONTACTO > NO ...|         Completado|16/05/2026 02:54:...|16/05/2026 02:55:...|            17|       Si|https://aiyou-upl...|           No|         No|             -|  NULL|   NULL| NULL|NULL|   46143|3565147|        0|    R7|    D1|Mayo 2026|        02 FLEXIBLE|   MES, PLD NO PEERS|BASE 2026-05-01|             R|        0|      0|    INDEPENDIENTE|NULL|     AREQUIPA|   CAMANA|MARIANO NICOLAS V...|        COMCCASIAHUI|           10600|             36|       43.8000|     706.4200|CREDICASH R / ELE...|                   1|   3. URB|       4|
| 22348|YANEE SORAIDA PUM...|957937328|        Contestadora|Buzón / No contesto|16/05/2026 02:54:...|                   -|          NULL|       No|                NULL|           No|         No|             -|  NULL|   NULL| NULL|NULL|   46143|3550225|        0|    R7|    D0|Mayo 2026|  01 SUPER FLEXIBLE|      MES, PLD PEERS|BASE 2026-05-01|             R|        1|      0|         INFORMAL|NULL|     AREQUIPA| AREQUIPA|      CERRO COLORADO|CALLE 28 DE JULIO...|           14800|             36|       33.6000|    1257.7200|CREDICASH R / ELE...|                   1|   3. URB|       0|
| 22349| TONNY VELA GALLARDO|935571761|        Contestadora|Buzón / No contesto|16/05/2026 02:54:...|                   -|          NULL|       No|                NULL|           No|         No|             -|  NULL|   NULL| NULL|NULL|   46143|3523901|949222763|    R7|    D0|Mayo 2026|        05 ESPECIAL|   NO MES, PLD PEERS|BASE 2026-05-01|             R|        0|      0|      DEPENDIENTE|NULL|       LORETO|   MAYNAS|            PUNCHANA|CLL MALECON TARAP...|            9300|             36|       33.6000|     247.0000|CREDICASH R / ELE...|                   1|   3. URB|       2|
| 22347|LUZ MARINA PARHUA...|925370821|        Contestadora|Buzón / No contesto|16/05/2026 02:54:...|                   -|          NULL|       No|                NULL|           No|         No|             -|  NULL|   NULL| NULL|NULL|   46143|3561561|        0|    R7|    D0|Mayo 2026|        02 FLEXIBLE|      MES, PLD PEERS|BASE 2026-05-01|             R|        1|      0|         INFORMAL|NULL|     AREQUIPA|   CAMANA|  JOSE MARIA QUIMPER|CIUDAD MUNICIPAL ...|            8000|             36|       33.6000|    1099.6400|CREDICASH R / ELE...|                   1|   3. URB|       4|
| 22350|   MONICA BRIO YUCRA|969996682|        Contestadora|Buzón / No contesto|16/05/2026 02:54:...|                   -|          NULL|       No|                NULL|           No|         No|             -|  NULL|   NULL| NULL|NULL|   46143|3577358|952000009|    R7|    D1|Mayo 2026|04 EN RECUPERACIÃ“N|   MES, PLD NO PEERS|BASE 2026-05-01|             R|        0|      0|    INDEPENDIENTE|NULL|        TACNA|    TACNA|        CIUDAD NUEVA|MZ D LT 07 ASOCIA...|           14200|             36|       36.3000|    2031.3300|CREDICASH R / ELE...|                   1|   3. URB|       4|
| 22344|ROSA ELIZABET MAC...|934850860|        Contestadora|Buzón / No contesto|16/05/2026 02:53:...|                   -|          NULL|       No|                NULL|           No|         No|             -|  NULL|   NULL| NULL|NULL|   46143|3572223|912168326|    R7|    D2|Mayo 2026|04 EN RECUPERACIÃ“N|      MES, PLD PEERS|BASE 2026-05-01|             R|        0|      0|         INFORMAL|NULL|        TACNA|    TACNA|CORONEL GREGORIO ...|ASOC VIV 28 DE AG...|            7300|             25|       55.6000|    1117.4300|CREDICASH R / ELE...|                   1|   3. URB|       4|
| 22334|ESTER QUISPE MAMA...|976271936|NO CONTACTO > NO ...|         Completado|16/05/2026 02:54:...|16/05/2026 02:54:...|            39|       Si|https://aiyou-upl...|           No|         No|             -|  NULL|   NULL| NULL|NULL|   46143|3576674|927862575|    R7|    D0|Mayo 2026|  01 SUPER FLEXIBLE|   MES, PLD NO PEERS|BASE 2026-05-01|             R|        0|      0|         INFORMAL|NULL|MADRE DE DIOS|TAMBOPATA|            INAMBARI| CPOBLADO PALMA REAL|           11300|             36|       40.8000|     659.9800|CREDICASH R / ELE...|                   1|   3. URB|       4|
| 22341|VICTORIA CALDERON...|950786662|        Contestadora|Buzón / No contesto|16/05/2026 02:54:...|                   -|          NULL|       No|                NULL|           No|         No|             -|  NULL|   NULL| NULL|NULL|   46143|3545909|995999955|    R7|    D0|Mayo 2026|  01 SUPER FLEXIBLE|NO MES, PLD NO PEERS|BASE 2026-05-01|             R|        0|      0|    INDEPENDIENTE|NULL|     APURIMAC|  ABANCAY|             ABANCAY|JR. TARACALLE MZA...|            7000|             36|       35.2000|     791.3900|CREDICASH R / ELE...|                   1|   3. URB|       4|
| 22330|BEATRIZ VERGARAY ...|916538025|        Contestadora|Buzón / No contesto|16/05/2026 02:54:...|                   -|          NULL|       No|                NULL|           No|         No|             -|  NULL|   NULL| NULL|NULL|   46143|3568680|        0|    R7|    D0|Mayo 2026|  01 SUPER FLEXIBLE|NO MES, PLD NO PEERS|BASE 2026-05-01|             R|        0|      0|    INDEPENDIENTE|NULL|MADRE DE DIOS|TAMBOPATA|           TAMBOPATA|JR. MARACANA MZA....|            7000|             32|       45.4000|     247.0000|CREDICASH R / ELE...|                   1|   3. URB|       4|
+------+--------------------+---------+--------------------+-------------------+--------------------+--------------------+--------------+---------+--------------------+-------------+-----------+--------------+------+-------+-----+----+--------+-------+---------+------+------+---------+-------------------+--------------------+---------------+--------------+---------+-------+-----------------+----+-------------+---------+--------------------+--------------------+----------------+---------------+--------------+-------------+--------------------+--------------------+---------+--------+
only showing top 10 rows

In [10]:
df_bot.filter(F.col('AGENCIA').isNull()).count()

32224

In [34]:
df_uno.count()

11393

In [44]:
df_bot.groupBy('seg_duracion') \
    .count() \
   .orderBy('seg_duracion') \
    .show(30, truncate=False)


print("Total registros:", df_bot.count())

+--------------+-----+
|seg_duracion  |count|
+--------------+-----+
|a. [0]        |25   |
|b. [1 - 15]   |8723 |
|c. [16 - 30]  |1610 |
|d. [31 - 45]  |648  |
|e. [46 - 60]  |137  |
|f. [106 - 120]|20   |
|f. [121 - 135]|21   |
|f. [136 - 150]|10   |
|f. [151 - 165]|11   |
|f. [166 - 180]|7    |
|f. [181 - 195]|5    |
|f. [196 - 210]|5    |
|f. [211 - 225]|4    |
|f. [226 - 240]|3    |
|f. [256 - 270]|1    |
|f. [271 - 285]|1    |
|f. [301 - 315]|2    |
|f. [61 - 75]  |72   |
|f. [76 - 90]  |45   |
|f. [91 - 105] |43   |
|z. null       |18277|
+--------------+-----+

Total registros: 29670

In [46]:
print([row['AGENCIA' ] for row in df_bot.select('AGENCIA').distinct().collect()])

['CARSA MOTOS_IQUITOS', 'CARSA_CHICLAYO', 'CARSA_SULLANA', 'MARCIMEX_ICA', 'CARSA_HUAYCAN', 'GMG_CARABAYLLO', 'CARSA_PIURA', 'CARSA MOTOS_PUCALLPA', 'CARSA_VIRU', 'CARSA_CAJABAMBA', 'CARSA_HUANCAYO', 'GMG_PUENTE PIEDRA', 'MARCIMEX_CAJAMARCA', 'CARSA_TAMBOGRANDE CENTRO', 'CARSA_JULIACA', 'CARSA_JAEN', 'MOTO GO_CUSCO', 'GMG_VES', 'CARSA MOTOS EXPRESS_CHIMBOTE', 'CARSA_HUAMACHUCO', 'CARSA_COMAS BELAUNDE', 'CARSA_ABANCAY', 'CARSA_PAITA', 'CARSA_YURIMAGUAS', 'CARSA_AREQUIPA NORTE', 'CARSA_TRUJILLO', 'CARSA_JUANJUI CENTRO', 'CARSA_AYACUCHO', 'GMG_VMT', 'CARSA_HUARMEY', 'CARSA_LA UNION', 'MOTO GO_JAEN', 'CARSA_NAZCA', None]

In [42]:
from pyspark.sql import functions as F

df_bot = df_bot.withColumn(

    'seg_duracion',

    F.when(
        F.col('Duracion (seg)').isNull(),
        'z. null'
    ).when(
        F.col('Duracion (seg)') == 0,
        'a. [0]'
    ).otherwise(

        F.concat(

            F.when(
                (((F.col('Duracion (seg)') - 1) / 15).cast('int') + 1) == 1,
                F.lit('b. ')
            ).when(
                (((F.col('Duracion (seg)') - 1) / 15).cast('int') + 1) == 2,
                F.lit('c. ')
            ).when(
                (((F.col('Duracion (seg)') - 1) / 15).cast('int') + 1) == 3,
                F.lit('d. ')
            ).when(
                (((F.col('Duracion (seg)') - 1) / 15).cast('int') + 1) == 4,
                F.lit('e. ')
            ).otherwise(
                F.lit('f. ')
            ),

            F.lit('['),

            (
                (((F.col('Duracion (seg)') - 1) / 15).cast('int') * 15) + 1
            ).cast('int'),

            F.lit(' - '),

            (
                (((F.col('Duracion (seg)') - 1) / 15).cast('int') * 15) + 15
            ).cast('int'),

            F.lit(']')
        )
    )
)

In [ ]:
['Codigo', 'Contacto', 'Telefono', 'Tipificacion', 'Estado', 'Fecha Inicio', 'Fecha Fin', 'Duracion (seg)', 'Grabacion', 'ruta_descarga', 'Se envio link', 'Lista negra', 'Grupo familiar', 'TIENDA', 'AGENCIA', 'FECHA', 'HORA', 'cl_carga', 'cl_id', 'cl_telf2', 'Region', 'PERFIL', 'cl_base', 'Semaforo', 'MARCA_PD', 'LOTE', 'GRUPO_SEGMENTO', 'FLG_PEARS', 'FLG_URB', 'SITUACION_LABORAL', 'MSI', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'DIRECCION', 'OFERTA_CREDICASH', 'PLAZO_CREDICASH', 'TASA_CREDICASH', 'CME_CREDICASH', 'PRODUCTO_EXTERNO', 'PROPENSION_CREDICASH', 'TIPO_ZONA', 'FRESCURA']du

['Codigo', 'Contacto', 'Telefono', 'Tipificacion', 'Estado', 'Fecha Inicio', 'Fecha Fin', 'Duracion (seg)', 'Grabacion', 'ruta_descarga', 'Se envio link', 'Lista negra', 'Grupo familiar', 'TIENDA', 'AGENCIA', 'FECHA', 'HORA', 'cl_carga', 'cl_id', 'cl_telf2', 'Region', 'PERFIL', 'cl_base', 'Semaforo', 'MARCA_PD', 'LOTE', 'GRUPO_SEGMENTO', 'FLG_PEARS', 'FLG_URB', 'SITUACION_LABORAL', 'MSI', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'DIRECCION', 'OFERTA_CREDICASH', 'PLAZO_CREDICASH', 'TASA_CREDICASH', 'CME_CREDICASH', 'PRODUCTO_EXTERNO', 'PROPENSION_CREDICASH', 'TIPO_ZONA', 'FRESCURA']

In [22]:
df_bot.show(2, truncate=False)

+------+-----------------------------------+---------+------------+-------------------+-------------------------+-------------------------+--------------+---------+------------------------------------------------------------------------------------------------------+-------------+-----------+--------------+------+-------+-----+----+--------+-------+---------+------+------+---------+-----------+-----------------+---------------+--------------+---------+-------+-----------------+----+------------+---------+-------------------------+-----------------------------------+----------------+---------------+--------------+-------------+-------------------------+--------------------+---------+--------+
|Codigo|Contacto                           |Telefono |Tipificacion|Estado             |Fecha Inicio             |Fecha Fin                |Duracion (seg)|Grabacion|ruta_descarga                                                                                         |Se envio link|Lista negra|Grupo familiar|TIENDA|AGENCIA|FECHA|HORA|cl_carga|cl_id  |cl_telf2 |Region|PERFIL|cl_base  |Semaforo   |MARCA_PD         |LOTE           |GRUPO_SEGMENTO|FLG_PEARS|FLG_URB|SITUACION_LABORAL|MSI |DEPARTAMENTO|PROVINCIA|DISTRITO                 |DIRECCION                          |OFERTA_CREDICASH|PLAZO_CREDICASH|TASA_CREDICASH|CME_CREDICASH|PRODUCTO_EXTERNO         |PROPENSION_CREDICASH|TIPO_ZONA|FRESCURA|
+------+-----------------------------------+---------+------------+-------------------+-------------------------+-------------------------+--------------+---------+------------------------------------------------------------------------------------------------------+-------------+-----------+--------------+------+-------+-----+----+--------+-------+---------+------+------+---------+-----------+-----------------+---------------+--------------+---------+-------+-----------------+----+------------+---------+-------------------------+-----------------------------------+----------------+---------------+--------------+-------------+-------------------------+--------------------+---------+--------+
|24915 |SALVADOR ALEJANDRO SALINAS CANTORAL|958732631|Contestadora|Completado         |18/05/2026 09:43:43 a. m.|18/05/2026 09:43:44 a. m.|2             |Si       |https://aiyou-uploads.s3.us-east-1.amazonaws.com/app/8/llamadas/2026-05-18/llamadas_20260518094344.mp3|No           |No         |-             |NULL  |NULL   |NULL |NULL|46143   |3548016|959830885|R7    |D2    |Mayo 2026|02 FLEXIBLE|MES, PLD NO PEERS|BASE 2026-05-01|R             |0        |1      |INDEPENDIENTE    |NULL|AREQUIPA    |AREQUIPA |MARIANO MELGAR           |URB EL MIRADOR DE MNO MELGAR 14 E14|11500           |36             |39.9000       |2086.6600    |CREDICASH R / ELECTRO MSI|1                   |2. NO URB|4       |
|24916 |REY CLAUDIO MANCILLA HUASHUAYO     |949110273|Contestadora|Buzón / No contesto|18/05/2026 09:43:33 a. m.|-                        |-             |No       |NULL                                                                                                  |No           |No         |-             |NULL  |NULL   |NULL |NULL|46143   |3551114|0        |R7    |D0    |Mayo 2026|02 FLEXIBLE|MES, PLD NO PEERS|BASE 2026-05-01|R             |0        |0      |DEPENDIENTE      |NULL|AREQUIPA    |CAMANA   |MARIANO NICOLAS VALCARCEL|CAL. 24 DE JUNIO NRO. S/N SECOCHA  |15000           |36             |26.8000       |1659.8400    |CREDICASH R / ELECTRO MSI|1                   |3. URB   |4       |
+------+-----------------------------------+---------+------------+-------------------+-------------------------+-------------------------+--------------+---------+------------------------------------------------------------------------------------------------------+-------------+-----------+--------------+------+-------+-----+----+--------+-------+---------+------+------+---------+-----------+-----------------+---------------+--------------+---------+-------+-----------------+----+------------+---------+-------------------------+-----------------------------------+----------------+---------------+--------------+-------------+-------------------------+--------------------+---------+--------+
only showing top 2 rows

In [5]:
print(df_bot.columns)

['Codigo', 'Contacto', 'Telefono', 'Tipificacion', 'Estado', 'Fecha Inicio', 'Fecha Fin', 'Duracion (seg)', 'Grabacion', 'ruta_descarga', 'Se envio link', 'Lista negra', 'Grupo familiar', 'TIENDA', 'AGENCIA', 'FECHA', 'HORA', 'cl_carga', 'cl_id', 'cl_telf2', 'Region', 'PERFIL', 'cl_base', 'Semaforo', 'MARCA_PD', 'LOTE', 'GRUPO_SEGMENTO', 'FLG_PEARS', 'FLG_URB', 'SITUACION_LABORAL', 'MSI', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'DIRECCION', 'OFERTA_CREDICASH', 'PLAZO_CREDICASH', 'TASA_CREDICASH', 'CME_CREDICASH', 'PRODUCTO_EXTERNO', 'PROPENSION_CREDICASH', 'TIPO_ZONA', 'FRESCURA']

In [ ]:
['Codigo', 'Contacto', 'Telefono', 'Tipificacion', 'Estado', 'Fecha Inicio', 'Fecha Fin', 'Duracion (seg)', 'Grabacion', 'ruta_descarga', 'Se envio link', 'Lista negra', 'Grupo familiar', 'TIENDA', 'AGENCIA', 'FECHA', 'HORA', 'cl_carga', 'cl_id', 'cl_telf2', 'Region', 'PERFIL', 'cl_base', 'Semaforo', 'MARCA_PD', 'LOTE', 'GRUPO_SEGMENTO', 'FLG_PEARS', 'FLG_URB', 'SITUACION_LABORAL', 'MSI', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'DIRECCION', 'OFERTA_CREDICASH', 'PLAZO_CREDICASH', 'TASA_CREDICASH', 'CME_CREDICASH', 'PRODUCTO_EXTERNO', 'PROPENSION_CREDICASH', 'TIPO_ZONA', 'FRESCURA']durac

In [7]:
df_bot.select('cl_id','Duracion (seg)').show()

+-------+--------------+
|  cl_id|Duracion (seg)|
+-------+--------------+
|3575777|             -|
|3567127|           195|
|3576681|             -|
|3564026|            10|
|3550064|             -|
|3556131|             9|
|3565147|            16|
|3576615|             2|
|3568915|             -|
|3527874|             -|
|3561561|             8|
|3579900|             -|
|3524554|             2|
|3567401|             -|
|3540920|             2|
|3550128|             -|
|3576188|             2|
|3526566|             2|
|3592048|             -|
|3583469|             2|
+-------+--------------+
only showing top 20 rows

In [ ]:
['cl_id', 'cabecera_carga', 'dni_cliente', 'contacto', 'id_servicio', 'mejor_codigo_cli_dia', 'mejor15_codigo_telf', 'mejor15_codigo_cli', 'mejor_codigo_cli', 'tipo_telf', 'cod_attempt', 'q_intentos_telef', 'indice_tpo_telf', 'contacto_02', 'min_numero', 'oferta_max', 'oferta_electro', 'tasa_electro', 'plazo_electro', 'cme_electro', 'oferta_credicash', 'tasa_credicash', 'plazo_credicash', 'cme_credicash', 'perfil', 'plazo', 'tasa', 'cme_disponible', 'lote', 'proveedor', 'msi', 'flg_credicash', 'propension', 'campana', 'cl_carga', 'obs_fcc', 'semaforo', 'region', 'tienda_ir', 'situacion_laboral', 'score_telefono', 'marca_pd', 'grupo_segmento', 'producto_externo', 'propension_electro', 'propension_credicash', 'flg_cruce_recurrente', 'alta_demanda', 'demanda', 'prioridad', 'inicio', 'retiro', 'fin', 'producto_interno', 'flg_aahh', 'intensidad_max', 'frescura', 'seg_oferta', 'seg_oferta_credicash', 'seg_oferta_electro', 'seg_tasa_credicash', 'seg_tasa_electro', 'seg_cme_electro', 'seg_cme_credicash', 'duracion', 'ult_codigo_result', 'fecha_llamada', 'dni_ejecutivo', 'dni_unico', 'mejor_estado_tipi_cli', 'mejor_sub_descripcion', 'mejor_descripcion_cli', 'mejor_peso_cli', 'mejor15_estado_tipi_cli', 'mejor15_descripcion_cli', 'mejor15_sub_descripcion_cli', 'mejor15_peso_cli', 'mejor15_estado_tipi_telf', 'mejor15_descripcion_telf', 'mejor15_sub_descripcion_telf', 'mejor15_peso_telf', 'mejor_estado_tipi_cli_dia', 'mejor_descripcion_cli_dia', 'mejor_sub_descripcion_cli_dia', 'mejor_peso_cli_dia', 'retiro4', 'estado_venta', 'lote_01']regi

In [ ]:
df_list.filter(F.col('fecha_llamada')=='2026-')

In [ ]:
df_list.filter(F.col('fecha_llamada')).groupBy('region') \
    .count() \
    .orderBy('region') \
    .show(30, truncate=False)

+-------------+-----+
|fecha_llamada|count|
+-------------+-----+
|NULL         |29046|
|2026-05-02   |2736 |
|2026-05-04   |6383 |
|2026-05-05   |10232|
|2026-05-06   |13660|
|2026-05-07   |9122 |
|2026-05-08   |10994|
|2026-05-09   |9456 |
|2026-05-11   |6046 |
|2026-05-12   |10441|
|2026-05-13   |11046|
|2026-05-14   |9215 |
+-------------+-----+

In [ ]:
df_list.groupBy('producto_externo') \
    .count() \
    .orderBy('producto_externo') \
    .show(30, truncate=False)

In [ ]:
df_list.dropDuplicates(['dni_cliente']).groupBy('lote_01') \
    .count() \
    .orderBy('lote_01') \
    .show(30, truncate=False)

print([row['lote_01' ] for row in df_list.select('lote_01').distinct().collect()])

+-----------------+-----+
|lote_01          |count|
+-----------------+-----+
|01.INVENTARIO    |76312|
|02. FRESCURA CERO|4536 |
|03.BASE CLIENTE  |11965|
|04.BASE REGULAR  |18315|
+-----------------+-----+

In [18]:
df_list_filtrada = df_parte_2.select(
    'cabecera_carga'
).toPandas()
ruta_archivo = os.path.join(ruta_csv, 'credicash_parte_2.xlsx')
df_list_filtrada.to_excel(ruta_archivo, index=False)

In [10]:
df_list.groupBy('tipo_telf') \
    .count() \
    .orderBy('tipo_telf') \
    .show(30, truncate=False)

+---------+------+
|tipo_telf|count |
+---------+------+
|cel01    |128293|
|cel02    |86    |
|cel08    |15487 |
|cel09    |9035  |
+---------+------+

In [11]:
df_list_filtrada = df_parte_3.select(
    'cabecera_carga',
).toPandas()
ruta_archivo = os.path.join(ruta_csv, 'df_parte_3.xlsx')
df_list_filtrada.to_excel(ruta_archivo, index=False)